- src/stitches.ts
> feat: add return type for stitches utils funcs

- package.json
- src/stitches.ts
- yarn.lock
- Replace hard-coded theme with package
- Include as peer and dev dependency
- Update `module` export to `esmodule` as per microbundle docs
> Feature: Theme package

- .github/workflows/main.yml
- .npmrc
- yarn.lock
- Added a simple Github action to run our tests and validate script on PRs into `main`
- Had to recreate our `yarn.lock` to ensure it's using the correct registry
> Add Github action to run tests

- src/primitives/button/Button.tsx
- src/primitives/button/__snapshots__/Button.test.js.snap
- src/primitives/button/stories/Button.stories.mdx
> Buttons advanced

- src/components/text/Text.stories.mdx
- src/components/text/Text.test.tsx
- src/components/text/Text.tsx
- src/components/text/__snapshots__/Text.test.tsx.snap
- src/components/text/index.ts
> Feat: add Text component

- CONTRIBUTING.md
- src/components/flex/Flex.stories.mdx
- src/components/grid/Grid.stories.mdx
Have removed the unnecessary folders and updated the contribution doc to explain the structure as we agreed on it
> docs: removed unnecessary stories folders for single mdx files

- src/components/input/__snapshots__/Input.test.tsx.snap
Unsure why this snapshot kept failing so I've updated it here and it should 🤞 fix ours tests on incoming PRs
> Fix: Input snapshot

- src/components/checkbox/Checkbox.tsx
- src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap
- src/components/input/Input.tsx
- src/components/input/__snapshots__/Input.test.tsx.snap
- src/components/select/Select.tsx
- src/components/select/__snapshots__/Select.test.tsx.snap
- src/stitches.ts
- Fixed token reference in boxShadows
- Ensure we're exporting all necessary functions from `createCss`
> Fix: Minor beta migration fixes

- src/components/textarea/Textarea.tsx
- src/components/textarea/__snapshots__/Textarea.test.tsx.snap
Adding the correct values for Textarea
> fix: added missing styling textarea

- CONTRIBUTING.md
- README.md
- package.json
- scripts/export-documentation.mjs
- src/components/box/Box.mdx
- src/components/button/Button.mdx
- src/components/button/Button.tsx
- src/components/button/__snapshots__/Button.test.tsx.snap
- src/components/checkbox/Checkbox.mdx
- src/components/flex/Flex.mdx
- src/components/grid/Grid.mdx
- src/components/heading/Heading.mdx
- src/components/icon/Icon.mdx
- src/components/image/Image.mdx
- src/components/input/Input.mdx
- src/components/label/Label.mdx
- src/components/link/Link.mdx
- src/components/link/Link.tsx
- src/components/radio/RadioButton.mdx
- src/components/select/Select.mdx
- src/components/text/Text.mdx
- src/components/textarea/Textarea.mdx
- src/components/validation-error/ValidationError.mdx
- yarn.lock
- Added categories to current component docs
- Tweaked a few of the component docs to show different examples or to fix formatting issues
- Updated `Button` & `Link` to improve compatibility with docs site
- Added a `watch` mode to docs build to preview documentation locally
> Feature: Documentation compatibility & dev workflows

- package.json
- rollup.config.js
- src/components/input-field/InputField.test.tsx
- tsconfig.json
- Set initial version to 0.1.0 alpha
- Fixed test and dev dependency
- Specified output files for package
- Removed source maps
> Chore: Publishing setup

- src/components/button/Button.mdx
- src/components/button/Button.test.tsx
- src/components/button/Button.tsx
- src/components/button/__snapshots__/Button.test.tsx.snap
https://recordit.co/8nFPSGstjb
> feat: Button loading state

- package.json
- src/components/form/Form.test.tsx
Tiny fix to `Form` test and release.
> Release 0.1.0 alpha.1

- src/components/input-field/InputField.tsx
- src/components/input-field/__snapshots__/InputField.test.tsx.snap
- src/components/label/Label.tsx
- src/components/label/__snapshots__/Label.test.tsx.snap
- src/components/password-field/PasswordField.tsx
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
Adjusts the space between input and label to be the same as in the atom core
> Fix tweaks for field components

- sandbox/index.tsx
- src/components/button/Button.tsx
- src/components/list/List.tsx
- src/components/list/__snapshots__/List.test.tsx.snap
* adds `mb` to `List.Item`s inside a `List`
* adds `fullWidth` variant to `Button`
> Feat: component updates for registration views

- src/components/label/Label.tsx
- src/components/link/Link.tsx
- src/components/link/__snapshots__/Link.test.tsx.snap
- src/components/list/List.tsx
- src/components/text/Text.tsx
- src/stitches.ts
Make capsize conditional on text size variants
> Fix: Link capsize

- src/components/divider/Divider.mdx
- src/components/divider/Divider.test.tsx
- src/components/divider/Divider.tsx
- src/components/divider/__snapshots__/Divider.test.tsx.snap
- src/components/divider/index.ts
- src/components/index.ts
> feat: add divider component

- src/components/text/Text.tsx
- src/components/text/__snapshots__/Text.test.tsx.snap
- src/components/validation-error/__snapshots__/ValidationError.test.tsx.snap
Removed the maxWidth from `Text` as we discussed on Wednesday.
> fix(text): removed  maxWidth

- package.json
Forgot to update the package version when releasing the other day
> Chore: Release 0.3.0

- LICENSE.md
https://choosealicense.com/licenses/gpl-3.0/
> Chore: Add LICENSE

- src/components/field-wrapper/__snapshots__/FieldWrapper.test.tsx.snap
- src/components/link/Link.mdx
- src/components/link/Link.tsx
- src/components/link/__snapshots__/Link.test.tsx.snap
- src/components/list/List.tsx
- Handle `Link` within `List`
- Add capsize documentation to `Link`
> Fix: Capsize list link

- src/components/toast/Toast.tsx
- src/components/toast/ToastProvider.test.tsx
- src/components/toast/ToastProvider.tsx
- src/components/toast/__snapshots__/ToastProvider.test.tsx.snap
Fix to add a z-index to the toast component
> Fix: add z-index to styled toast

- src/components/search-input/SearchInput.mdx
- src/components/search-input/SearchInput.test.tsx
- src/components/search-input/SearchInput.tsx
- src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
- src/components/search-input/index.ts
Keen to get some thoughts on creating a search input for the design system, it'll only be an icon and a search input type but I think for consistency it'll be worth including.
> Feature: Search input

- src/components/field-wrapper/__snapshots__/FieldWrapper.test.tsx.snap
- src/components/input-field/__snapshots__/InputField.test.tsx.snap
- src/components/input/Input.tsx
- src/components/input/__snapshots__/Input.test.tsx.snap
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap
- src/components/select-field/__snapshots__/SelectField.test.tsx.snap
- src/components/select/Select.tsx
- src/components/select/__snapshots__/Select.test.tsx.snap
Have seen this smaller form field convention used across a few incoming features, not sure it should be applicable to password, checkbox/radio or textarea, I guess combobox should also allow a small size input as well.
> Feature: Small form fields

- src/components/action-icon/ActionIcon.mdx
- src/components/action-icon/ActionIcon.tsx
- src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap
Added 'isRounded' prop to ActionIcon
> Feat add action icon isRounded

- src/components/action-icon/ActionIcon.tsx
- src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap
- src/components/button/Button.tsx
- src/components/button/__snapshots__/Button.test.tsx.snap
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap
- Removed "subtle" variant
- Updated theme variants to always show a theme color rather than grey
- Updated disabled state to be consistent across appearances
- Added a white background to each variant to improve legibility on other background colors
> Action icon / Button variants

- src/components/action-icon/ActionIcon.tsx
- src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap
Adjusts ActionIcon's disabled state colours.
> Adjust action icon disabled state colours

- src/components/action-icon/ActionIcon.tsx
- src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap
- src/components/dialog/DialogContent.tsx
- src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- src/components/password-input/PasswordInput.tsx
- src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap
- src/components/popover/PopoverContent.tsx
Any thoughts on the name here? We're going to need a "grey" icon with hover state for `PasswordInput` visibility toggle, Dialog Close buttons, etc. etc.
> Fix: Action icon neutral theme

- src/components/checkbox-field/CheckboxField.tsx
- src/components/form/Form.test.tsx
- src/components/input-field/InputField.tsx
- src/components/input-field/__snapshots__/InputField.test.tsx.snap
- src/components/password-field/PasswordField.tsx
- src/components/radio-field/RadioGroupField.tsx
- src/components/select-field/SelectField.tsx
- src/components/textarea-field/TextareaField.tsx
> Fix: Remove `required` prop

- src/components/tabs/TabTrigger.tsx
- src/components/tabs/__snapshots__/Tabs.test.tsx.snap
> Fix: remove cursor pointer from disabled tab

- src/components/dropdown-menu/DropdownMenu.mdx
- src/components/dropdown-menu/DropdownMenuItem.tsx
- src/components/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap
Adds hover styles for dropdown items and fixes documentation mistakes
> feat: update dropdown item styles

- package.json
- src/components/accordion/Accordion.mdx
- src/components/accordion/Accordion.test.tsx
- src/components/accordion/Accordion.tsx
- src/components/accordion/AccordionContent.tsx
- src/components/accordion/AccordionItem.tsx
- src/components/accordion/AccordionTrigger.tsx
- src/components/accordion/__snapshots__/Accordion.test.tsx.snap
- src/components/accordion/index.ts
- src/components/index.ts
- yarn.lock
Adding an Accordion component because it is needed for a ticket. The Accordion is taken from Radix and has been styled to fit the design system.
https://user-images.githubusercontent.com/66493855/141107043-b49e84bf-aaa7-4ee9-b851-b8afb6902025.mov
> feat: Accordion Component

- src/components/table/Table.tsx
- src/components/table/TableCell.tsx
- src/components/table/TableHeader.tsx
- src/components/table/TableHeaderCell.tsx
- src/components/table/TableRow.tsx
- src/components/table/__snapshots__/Table.test.tsx.snap
Updates table styles after some changes to designs and some resolved miscommunications.
> Patch: more table styles

- src/components/action-icon/ActionIcon.tsx
Added additional ActionIcon variants form primaryDark colors.
> feat: additional icon variant

- src/components/tabs/Tabs.tsx
- src/components/tabs/TabsTriggerList.tsx
- src/components/tabs/__snapshots__/Tabs.test.tsx.snap
1. Removed background from tabs container
2. Use `window` inside of `useEffect` to fix SSR build
> fix: css as per designs + SSR build

- package.json
- yarn.lock
This PR updates the theme package to `1.0.1`
> fix: update theme package

- src/components/search-input/SearchInput.mdx
- src/components/search-input/SearchInput.test.tsx
- src/components/search-input/SearchInput.tsx
- src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
**Tasks:**
**Ticket:**
https://www.pivotaltracker.com/story/show/180313561
**Recording:**
https://recordit.co/simbbNVZhG
Closes https://github.com/Atom-Learning/components/issues/244
> SearchInput updates

- src/components/accordion/Accordion.tsx
Minor type update to allow the CSS prop
> fix: extend type to allow passing CSS

- lib/src/components/badge/Badge.tsx
- lib/src/components/badge/__snapshots__/Badge.test.tsx.snap
- site/src/utilities/get-page-data.ts
This PR fixes the badge component height as well as the component view source URL.
https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-87
- Fixes the component view source URL in the site docs
- Fixes the badge heights to use the DS space scales
> Fix: Badge component wrong height

- lib/src/components/stepper/StepperStepBullet.tsx
- lib/src/components/stepper/StepperStepContainer.tsx
- lib/src/components/stepper/StepperStepLabel.tsx
- lib/src/components/stepper/StepperSteps.tsx
- lib/src/components/stepper/__snapshots__/Stepper.test.tsx.snap
> Fix: Stepper responsive styles

- lib/src/components/stepper/StepperStepBullet.tsx
- lib/src/components/stepper/StepperStepContainer.tsx
- lib/src/components/stepper/StepperStepLabel.tsx
- lib/src/components/stepper/StepperSteps.tsx
- lib/src/components/stepper/__snapshots__/Stepper.test.tsx.snap
- lib/src/components/stepper/stepper-context/StepperContext.tsx
- lib/src/components/stepper/types.ts
- site/src/sandbox/components.tsx
[Jira](https://atomlearningltd.atlassian.net/browse/PAG-182)
Update DS stepper component to match the new requirements of design review [found here](https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=5770%3A44681)
Fix bug showcasing component in documentation site.
> Update stepper component

- site/src/components/Scale.tsx
A pretty small one, this displays the px value of our scales.
https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-114
> Display px value in docs

- lib/src/components/badge/Badge.mdx
- lib/src/components/badge/Badge.test.tsx
- lib/src/components/badge/Badge.tsx
- lib/src/components/badge/__snapshots__/Badge.test.tsx.snap
Ticket https://atomlearningltd.atlassian.net/browse/DS-28
Designs https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=4006%3A15616&t=ogXGJhpQHmSSjNLd-0
- Updated font sizes and colours as per designs
- `React.Children.map` and clone has been used to add props to icon
> chore: updated badge component

- documentation/public/admin/config.yml
https://atom-learning.slack.com/archives/G01G926F9DM/p1676641280189729?thread_ts=1676640883.102659&cid=G01G926F9DM
One line change to merge asap
> feat: move to new ds url

- lib/src/components/action-icon/ActionIcon.tsx
- lib/src/components/date-field/__snapshots__/DateField.test.tsx.snap
- lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap
- lib/src/components/dialog/DialogContent.tsx
- lib/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
- lib/src/components/number-input-field/__snapshots__/NumberInputField.test.tsx.snap
- lib/src/components/number-input/__snapshots__/NumberInput.test.tsx.snap
- lib/src/components/popover/PopoverContent.tsx
- Fixing a couple tooltips that needed to be turned off (Dialog Close button and popover)
> Fix: Action icon missed edge cases

- documentation/content/components.surfaces.tile-interactive.md
- documentation/content/components.surfaces.tile-toggle-group.md
- documentation/content/components.surfaces.tile.md
- lib/src/components/index.ts
- lib/src/components/tile-interactive/TileInteractive.test.tsx
- lib/src/components/tile-interactive/TileInteractive.tsx
- lib/src/components/tile-interactive/__snapshots__/TileInteractive.test.tsx.snap
- lib/src/components/tile-interactive/index.ts
- lib/src/components/tile-toggle-group/TileToggleGroup.test.tsx
- lib/src/components/tile-toggle-group/TileToggleGroupItem.tsx
- lib/src/components/tile-toggle-group/TileToggleGroupRoot.tsx
- lib/src/components/tile-toggle-group/__snapshots__/TileToggleGroup.test.tsx.snap
- lib/src/components/tile-toggle-group/index.ts
- lib/src/components/tile/Tile.test.tsx
- lib/src/components/tile/Tile.tsx
- lib/src/components/tile/TileGroup.tsx
- lib/src/components/tile/TileNoOverflowContainer.tsx
- lib/src/components/tile/__snapshots__/Tile.test.tsx.snap
- lib/src/components/tile/index.ts
- lib/src/utilities/no-overflow-container/NoOverflowContainer.test.tsx
- lib/src/utilities/no-overflow-container/NoOverflowContainer.tsx
- lib/src/utilities/no-overflow-container/__snapshots__/NoOverflowContainer.test.tsx.snap
- lib/src/utilities/no-overflow-container/index.ts
**Tile** is a fundamental layout component used as a generic container to build the base of panels, cards, lists and other content components that group information. 
**TileInteractive** is the button variation which allows for href or onClick handlers.
**TileToggleGroup** is the... toggle group version - which allows for selecting the tiles.
All built wrapped with `ColorScheme` to allow for multiple colour palette setups.
JIRA: https://atomlearningltd.atlassian.net/browse/DS-352
Figma: https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=6096-44675&t=bvcqbBYJGTw9NesH-0
**Tile (base)**
**TileInteractive**
https://user-images.githubusercontent.com/6905473/226906008-fdb8ac88-e7f3-48ce-949c-96e59256f86e.mov
**TileToggleGroup** …
> feat: Tile

- documentation/components/markdown/editor-component/Cards.tsx
- documentation/components/markdown/editor-component/DosAndDonts.tsx
> fix: make cards and dos and donts backgrounds grey

- documentation/package.json
- lib/package.json
- yarn.lock
As there are new icons available that we can use to replace font awesome.
> feat: bump icons version

- .github/workflows/auto-fix.yml
I think this is fine now? Have tried running locally to make sure but it's proving to be PITA so I'm just assuming the problem was the `:` all along and this is fine :o 
input welcome
> fix: auto-fix bad yml

- documentation/components/markdown/editor-component/ColorTokenList.tsx
- documentation/components/markdown/editor-component/FontFamilyTokenList.tsx
- documentation/components/markdown/editor-component/FontSizeTokenList.tsx
- documentation/components/markdown/editor-component/RadiusTokenList.tsx
- documentation/components/markdown/editor-component/ShadowTokenList.tsx
- documentation/components/markdown/editor-component/SizeTokenList.tsx
- documentation/components/markdown/editor-component/SpaceTokenList.tsx
Fixes https://atom-learning.slack.com/archives/G01G926F9DM/p1682496172202549
Copied solution from `atom-core` uses of `atomTheme`
> chore: fix atomTheme typescript errors

- lib/src/components/pagination/PaginationItem.tsx
- lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap
Making the positioning CSS of the Dot a bit more predictable/less random-number based :)
> feat: make Dot positioning CSS a bit cleaner

- lib/src/components/banner/banner-regular/BannerRegularActions.tsx
- lib/src/components/banner/banner-regular/__snapshots__/BannerRegular.test.tsx.snap
No visual changes expected
Before : 
After :
> chore: Replace deprecated Stack component with Flexbox and update tests for BannerRegularActions

- lib/src/components/navigation-menu-vertical/NavigationMenuVertical.styles.ts
- lib/src/components/navigation-menu-vertical/NavigationMenuVertical.tsx
- lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap
- lib/src/components/navigation-menu-vertical/stitches.navigationMenuVertical.colorscheme.config.ts
> feat: add theming vars to NavigationMenuVertical

- lib/package.json
- yarn.lock
Updating icons library to the latest version
> feat: updating icons library

- lib/package.json
- yarn.lock
Bumping icons library version that contains new icons
> feat: bumping icons library version

- lib/src/components/input/Input.tsx
[This one didn't work ](https://github.com/Atom-Learning/components/pull/672)
but maybe the issue is the forwardRef types a la https://github.com/Atom-Learning/components/pull/625/files#diff-8ad291893c161e2ca617e0865d03e2140db3ff9edc8f864a196369ca3b9075a9
> fix: Input forwardRef type

- package.json
Set the Node version for DO (Documentation site).
> fix: set node version for DO

- lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap
- lib/src/components/search-field/__snapshots__/SearchField.test.tsx.snap
- lib/src/components/search-input/SearchInput.tsx
- lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
After recent change width became 100% which breaks styling in core. reverting.
> fix: readd auto width to search input
