src/stitches.ts
Fixes the name of our `tonal` colors so that they get darker as the number in their names increase.
=> Chore: fix tonal colors order

.babelrc, .github/workflows/main.yml, .gitignore, .prettierignore, package.json, yarn.lock
- Set correct `NODE_ENV` value for builds
- Pointing exports to the correct output files
- Fixed the package name
- Added `babel-plugin-react-remove-properties` to remove any `testid`s from the bundle and `babel-plugin-transform-stitches-display-name` to automatically add `displayName` to `styled()` components
- Updated the github action install command to remove the `--frozen-lockfile` arg
=> Local environment and output fixes

package.json, src/components/input/Input.tsx, src/components/input/__snapshots__/Input.test.tsx.snap, tsconfig.json, yarn.lock
- Beta 4 exports the correct JS type, need to figure out why the snapshots update though, the ID should remain constant
- Had to update `Input` component to simplify the component type and remove test files from being type checked
=> Fix: Update @atom-learning/theme to beta 4

package.json, rollup.config.js, src/components/icon/Icon.tsx, src/components/icon/__snapshots__/Icon.test.tsx.snap, src/components/icon/svg/index.ts, tsconfig.json, yarn.lock
Fixes problems with importing SVGs as React components and with passing them to the `Icon` component's `is` prop.
=> fix: svg import issues and Icon prop types

package.json
We lost type declarations (`.d.ts` files) from our `dist` directory when we switched TypeScript plugins for rollup. This change restores them.
=> fix: output type declarations

src/components/password-field/PasswordField.tsx, src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
- Tweak icon size to increase the hit area, knock back the color a bit to a dark grey, use `size` scale values
- Ensure focus is retained on input
- Ensure form is not submitted on click of icon
https://user-images.githubusercontent.com/3226804/110348482-9d89cb80-8029-11eb-9b7a-930cf62dda60.mov
=> Fix: Password field visibility

src/components/button/Button.test.tsx, src/components/button/Button.tsx, src/components/link/Link.test.tsx, src/components/link/Link.tsx
Makes `Button` polymorphic by overriding its `as` prop to accept `React.ElementType` | `React.ComponentType`.
This allows us to wrap `Button` with logic to render as an `a` or `react-router` `Link` in `seahorse`, but is probably over-permissive. We should revisit this as we get more experience with realistic requirements and hopefully we can narrow the scope of the `as` prop.
I also updated the `onClick` behaviour so that no function is called at all if no `onClick` is passed. This is to ensure that the click handler in `Button` doesn't get in the way of the default behaviour of an `a`.
=> Feat: polymorphic button

src/components/box/Box.tsx, src/components/flex/Flex.tsx
- Remove custom component export to retain `as` types
=> Fix: Layout component types

src/components/button/Button.tsx, src/components/link/Link.tsx
These should be optional to allow standard component rendering e.g. `<Link href="http://hello.com">Hello</Link>`
=> Fix: Optional `as` for `Button` and `Link`

CONTRIBUTING.md, src/components/box/Box.mdx, src/components/button/Button.mdx, src/components/checkbox/Checkbox.mdx, src/components/icon/Icon.mdx, src/components/image/Image.mdx, src/components/input-field/InputField.mdx, src/components/input/Input.mdx, src/components/label/Label.mdx, src/components/link/Link.mdx, src/components/list/List.mdx, src/components/loader/Loader.mdx, src/components/password-field/PasswordField.mdx, src/components/popover/Popover.mdx, src/components/progress-bar/ProgressBar.mdx, src/components/select/Select.mdx, src/components/text/Text.mdx, src/components/textarea/Textarea.mdx, src/components/validation-error/ValidationError.mdx, src/components/video/Video.mdx
- Removing `center` option as all previews now center
- Changed one or two categories (all tbc just conforming to our current structure)
=> Minor docs update

package.json, src/components/box/__snapshots__/Box.test.tsx.snap, src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap, src/components/flex/__snapshots__/Flex.test.tsx.snap, src/components/grid/__snapshots__/Grid.test.tsx.snap, src/components/heading/__snapshots__/Heading.test.tsx.snap, src/components/icon/__snapshots__/Icon.test.tsx.snap, src/components/input-field/__snapshots__/InputField.test.tsx.snap, src/components/input/__snapshots__/Input.test.tsx.snap, src/components/label/__snapshots__/Label.test.tsx.snap, src/components/link/__snapshots__/Link.test.tsx.snap, src/components/list/__snapshots__/List.test.tsx.snap, src/components/loader/__snapshots__/Loader.test.tsx.snap, src/components/password-field/__snapshots__/PasswordField.test.tsx.snap, src/components/popover/Popover.tsx, src/components/popover/__snapshots__/Popover.test.tsx.snap, src/components/progress-bar/__snapshots__/ProgressBar.test.tsx.snap, src/components/radio/__snapshots__/RadioButton.test.tsx.snap, src/components/radio/__snapshots__/RadioButtonGroup.test.tsx.snap, src/components/select/__snapshots__/Select.test.tsx.snap, src/components/text/__snapshots__/Text.test.tsx.snap, src/components/textarea/__snapshots__/Textarea.test.tsx.snap, src/components/validation-error/__snapshots__/ValidationError.test.tsx.snap, src/components/video/__snapshots__/Video.test.tsx.snap, src/stitches.ts, src/utilities/css-wrapper/__snapshots__/CSSWrapper.test.tsx.snap, src/utilities/storybook.ts, tsconfig.json, yarn.lock
- Upgrade stitches to latest beta (pretty sure this is the release candidate, aside from hotfixes)
- ~Upgraded Radix packages to include new hotfixes (aside from radiogroup which has an issue when testing)~
- Fixed a TS issue in `PopOver` (we didn't need to spread content and root types into the prop types)
- Removed a storybook utility
- Added `"skipLibCheck": true` to our TS config to bypass some internal TS errors within stitches
The snapshot changes seem to be:
- changed how classes are named
- some class duplication merged into a single selector
- prefixing `appearance`
=> Feature: Upgrade stitches

package.json, scripts/add-component.mjs, src/components/button/Button.test.tsx, src/components/checkbox/Checkbox.test.tsx, src/components/divider/Divider.test.tsx, src/components/form/Form.test.tsx, src/components/heading/Heading.test.tsx, src/components/icon/Icon.test.tsx, src/components/icon/__snapshots__/Icon.test.tsx.snap, src/components/image/Image.test.tsx, src/components/input-field/InputField.test.tsx, src/components/input-field/__snapshots__/InputField.test.tsx.snap, src/components/input/Input.test.tsx, src/components/label/Label.test.tsx, src/components/link/Link.test.tsx, src/components/list/List.test.tsx, src/components/loader/Loader.test.tsx, src/components/password-field/PasswordField.test.tsx, src/components/popover/Popover.test.tsx, src/components/popover/__snapshots__/Popover.test.tsx.snap, src/components/progress-bar/ProgressBar.test.tsx, src/components/radio/RadioButton.test.tsx, src/components/radio/__snapshots__/RadioButton.test.tsx.snap, src/components/select/Select.test.tsx, src/components/text/Text.test.tsx, src/components/textarea/Textarea.test.tsx, src/components/validation-error/ValidationError.test.tsx, src/components/video/Video.test.tsx, src/documentation/accessibility.mdx
This separates tests into individual concerns (snapshot and axe). 
Note: in a couple of places I have removed the accessibility testing as it was unnecessary
Note2: in a couple of places I have removed unnecessary snapshot tests (ie: in popover)
=> Chore: separate tests

sandbox/index.tsx, src/components/button/Button.test.tsx, src/components/button/Button.tsx
Updates `Button` to render an `a` tag if optional `to` prop is provided.
=> feat: update Button to render anchor if provided link

package.json, scripts/export-documentation.mjs, src/components/input-field/InputField.mdx, src/components/password-field/PasswordField.mdx, src/components/radio-field/RadioField.mdx, src/components/select-field/SelectField.mdx, src/components/textarea-field/TextareaField.mdx, src/components/toast/Toast.mdx
- Wrap form field components in `Form` where needed (I'll add a ticket to deal with the error when `Form` isn't used)
- Filter out license from documentation export
- Change Toast documentation to `preview` as it's not a direct react component being rendered
- Bumped version to `0.4.1` as I'll publish once this is merged
=> Fix: Errored documentation

src/components/select-field/SelectField.mdx, src/components/select-field/SelectField.test.tsx, src/components/select-field/SelectField.tsx, src/components/select/Select.mdx, src/components/select/Select.test.tsx, src/components/select/Select.tsx, src/components/select/__snapshots__/Select.test.tsx.snap
Interested in your thoughts on this change to the `Select` component, I've been mulling this over for a few weeks and I don't think there's any reason to abstract the options into a prop, we can use the standard `<option>` HTML syntax and pass them as `children`.
Currently each options attributes are passed one by one onto the internal `<option>` element, which prevents using other standard attributes like `selected` (an easy fix by spreading the attributes but highlights the larger issue of flexibility/customisation). We also prevent using other standard `select` children like `optgroup` by abstracting `options`.
=> RFC: Select API

package.json, sandbox/index.tsx, src/components/form/Form.mdx, src/components/form/Form.test.tsx, src/components/form/Form.tsx
Adds `render` prop to `Form` component, giving access to everything returned by the internal `useForm()` call. 
I added it as a prop rather than using `children` because I found [this article](https://americanexpress.io/faccs-are-an-antipattern/) on the subject pretty compelling and because it's consistent with how `react-hook-form`'s own components (`Controller`) achieve the same thing.
=> Feat: update Form to take render prop

src/components/list/List.tsx, src/components/list/__snapshots__/List.test.tsx.snap
These changes should prevent issues where you'd set the text color of the List items (either on the `<List.Item />` itself or one of its ancestors and the markers would keep the `$tonal900` color because the `tonal` theme was set as default.
=> feat: Remove default List marker color

src/components/button/Button.mdx, src/components/button/Button.test.tsx, src/components/button/Button.tsx, src/components/link/Link.mdx, src/components/link/Link.tsx, src/types/index.ts, src/types/navigatorActions.types.ts
This PR is an answer on following issue:
https://github.com/Atom-Learning/components/issues/148
Changes:
Support Polymorphic feature for Link and Button.
Link can render anchor or button depends on passed properties (onClick / href)
Button can render button or anchor depends on passed properties (onClick / href)
=> feat: polymorphic link and button

src/components/button/Button.tsx, src/components/password-field/__snapshots__/PasswordField.test.tsx.snap
When using the library in another project, the margin on `<Icon />` inside a `<Button />` was not applied. This was because the margin was applied on components with the name `'icon'`. This name was minified, so the condition always resulted in a `false` when using the library.
Updated the condition to check if the child is an instance of the `Icon` component instead of checking the name.
_Note: the snapshot test for `PasswordField` failed. Decided to update that and include it here as it only changed the order of CSS._
=> fix: updated condition to apply margin on Icon inside Button

package.json, src/components/form/Form.mdx, src/components/form/Form.test.tsx, src/components/form/Form.tsx, src/components/form/Form.types.ts
Linked issue - https://github.com/Atom-Learning/components/issues/165
=> feat(persist-form): adding react-hook-form-persist package

src/components/markdown-content/MarkdownContent.mdx, src/components/markdown-content/MarkdownContent.tsx, src/components/markdown-content/__snapshots__/MarkdownContent.test.tsx.snap, src/components/stack-content/StackContent.tsx
=> Fix markdown content bugs

src/components/checkbox-field/CheckboxField.tsx, src/components/checkbox-field/__snapshots__/CheckboxField.test.tsx.snap, src/components/field-wrapper/FieldWrapper.mdx, src/components/field-wrapper/InlineFieldWrapper.tsx, src/components/radio-field/__snapshots__/RadioField.test.tsx.snap, src/components/switch/Switch.tsx, src/components/switch/__snapshots__/Switch.test.tsx.snap
`Switch` and `Input`/`Select` children within `InlineFieldWrapper` were throwing off the alignment, I updated `Switch` to the new design and tweaked a few layout props to allow more flexibility with alignment.
=> Fix: Inline field wrapper alignment

src/components/button/Button.tsx, src/components/button/__snapshots__/Button.test.tsx.snap
Fix to allow button to maintain its intended rollover state despite the presence of external CSS
Hover before:
Hover after:
=> fix: rollover stext color fixed to white

src/components/table/Table.mdx, src/components/table/Table.test.tsx, src/components/table/Table.tsx, src/components/table/TableCell.tsx, src/components/table/TableFooterCell.tsx, src/components/table/TableHeaderCell.tsx, src/components/table/__snapshots__/Table.test.tsx.snap
Adding styling changes using the new brand colours:
- Changing the header colour and border-radius
- Colouring every other row for better readability
- Creating a larger row to keep internal controls/buttons clickable in smaller devices
=> Feat: table styling updates

src/components/alert-dialog/AlertDialog.mdx, src/components/alert-dialog/alert-context/AlertContext.tsx, src/components/alert-dialog/alert-context/AlertDialog.tsx, src/components/alert-dialog/alert-context/types.ts
- Make the `cancelActionText` optional
- Tweak the docs to make it a little easier to read
- Update the `useAlert` hook to better communicate errors
=> Fix: Optional ActionDialog cancelActionText

src/components/toast/Toast.tsx, src/components/toast/ToastProvider.tsx, src/components/toast/__snapshots__/ToastProvider.test.tsx.snap
- Minor update to ensure toasts handle smaller viewport sizes and multi-line text
=> Fix: Toast responsive/adaptive styles

src/components/tabs/TabTrigger.tsx, src/components/tabs/Tabs.tsx
Reversed active/inactive colors; replaced old colors with v1.0 counterparts
=> Fix: Update Tabs colors to v1.0 versions

src/components/action-icon/ActionIcon.test.tsx, src/components/alert-dialog/alert-context/AlertContext.tsx, src/components/markdown-content/MarkdownContent.test.tsx, src/utilities/use-is-mounted-ref/index.ts, test/custom-assertions/expect-to-throw.ts
- Remove thrown errors from stdout in tests
- Ensure AlertDialog is mounted before removing
- Update MarkdownContent test case with valid HTML
=> Fix: Test warnings

src/components/checkbox-field/CheckboxField.mdx, src/components/checkbox/Checkbox.mdx, src/components/combobox/Combobox.mdx, src/components/field-wrapper/FieldWrapper.mdx, src/components/form/Form.mdx, src/components/input-field/InputField.mdx, src/components/input/Input.mdx, src/components/label/Label.mdx, src/components/password-field/PasswordField.mdx, src/components/password-input/PasswordInput.mdx, src/components/radio-field/RadioField.mdx, src/components/radio/RadioButton.mdx, src/components/search-input/SearchInput.mdx, src/components/select-field/SelectField.mdx, src/components/select/Select.mdx, src/components/switch/Switch.mdx, src/components/table/Table.mdx, src/components/tabs/Tabs.mdx, src/components/textarea-field/TextareaField.mdx, src/components/textarea/Textarea.mdx, src/components/validation-error/ValidationError.mdx
- Separate `Forms` category into `Form primitives` and `Form fields`, this should help when using the docs to find the specific primitive form component (`Input`, `Select`, `Checkbox`, `Label` etc.) or field component (`InputField`, `TextareaField`, etc.)
- Simplify our `Tabs` documentation as we had a few repeated code examples
- Moved `Table` to `Content` instead of `Layout`
=> Chore: Update documentation for RC

src/components/checkbox-field/__snapshots__/CheckboxField.test.tsx.snap, src/components/field-wrapper/__snapshots__/FieldWrapper.test.tsx.snap, src/components/heading/Heading.tsx, src/components/input-field/__snapshots__/InputField.test.tsx.snap, src/components/label/Label.test.tsx, src/components/label/Label.tsx, src/components/label/__snapshots__/Label.test.tsx.snap, src/components/password-field/__snapshots__/PasswordField.test.tsx.snap, src/components/radio-button-field/__snapshots__/RadioButtonField.test.tsx.snap, src/components/select-field/__snapshots__/SelectField.test.tsx.snap, src/components/text/Text.tsx, src/components/textarea-field/__snapshots__/TextareaField.test.tsx.snap
- Removed hard-coded `size` type from `Heading` and `Text` - We're constraining the valid props for `size` by using our own, and removing the ability to use media queries e.g. `<Heading size={{ '@initial': 'sm', '@md': 'lg' }} />`
- Removed unnecessary `align` and `direction` variants applying when `<Label type="block" />`
=> Fix: TS improvements and fixes

babel.config.json, package.json, yarn.lock
No longer necessary now we've changed our test for `CSSWrapper`
=> Chore: Remove unused babel plugin - "react-remove-properties"

package.json
Issue : 
Intellisense did not work for Typescript imports / props from `@atom-learning/components`.
Fix : 
Added `"typings": "dist/index.d.ts"` to `package.json`
=> fix: add typings to package.json to explicitly refer index.d.ts

package.json, sandbox/index.html, src/components/action-icon/ActionIcon.tsx, src/components/tabs/TabTrigger.tsx, src/components/tabs/Tabs.mdx, src/components/tabs/Tabs.test.tsx, src/components/tabs/Tabs.tsx, src/components/tabs/TabsTriggerList.tsx, src/components/tabs/__snapshots__/Tabs.test.tsx.snap, src/components/tabs/utils.ts, yarn.lock
1. Based on total width of tab container and screen size, show `<` & `>` buttons to allow easy scrolling of tabs.
2. Scroll amount is at 25% of tab container width
3. Conditionally show / hide scroll buttons
4. Bring the components up to new design - supporting two variations
```typescript
<Tabs appearance="light"></Tabs>
<Tabs appearance="dark"></Tabs>
```
https://user-images.githubusercontent.com/1936119/142402905-7f749c94-1704-4724-b0a5-5ae5db754703.mov
https://user-images.githubusercontent.com/1936119/142402968-9b3edec9-949a-44e0-a218-59de1c583e55.mov
=> Fix: Tabs mobile view

src/components/table/Table.mdx, src/components/table/Table.test.tsx, src/components/table/Table.tsx, src/components/table/TableHeader.tsx, src/components/table/TableHeaderCell.tsx, src/components/table/TableRow.tsx, src/components/table/__snapshots__/Table.test.tsx.snap
Added a few options to the table as they were needed for use with Accordions, and will likely be useful in the future elsewhere.
- `<Table applyRadius="false">` stops borderRadius being applied, useful if your container has a radius and multiple radiuses look odd. Default is `true`.
- `<Table.Header theme="primary">` changes the colour of the header rows. Options are `primary` and `primaryDark`. Default is `primaryDark`.
=> feat: adding new table variants

src/components/form/Form.types.ts
For some reason, we had `validationMode` restricted to `onBlur` | `onSubmit`. This MR picks values directly from `react-hook-form`
=> fix: proper types for validationMode

src/components/tabs/TabTrigger.tsx, src/components/tabs/Tabs.tsx, src/components/tabs/__snapshots__/Tabs.test.tsx.snap
New styling on the Tabs component assumes a white background for its light theme. I do not believe this should be assumed by the component, and removing the background makes this work with other light colours well, such as `$primaryLight` which we use a lot as a background. Hover background is still applied fine, so there's no real downside, it simply passes the responsibility of background colour to wherever is more appropriate.
with changes:
without (thing that prompted me this was an issue):
=> feat: no light bg for tabs

src/components/tabs/TabTrigger.tsx, src/components/tabs/Tabs.mdx, src/components/tabs/TabsTriggerList.tsx, src/components/tabs/__snapshots__/Tabs.test.tsx.snap
Tab triggers were recently made uppercase by default, but design have said that this should be optional as we do not want all tabs to be uppercase. Simple change to allow an uppercase prop.
`<Tabs.TriggerList uppercase>...</Tabs.TriggerList>`
Uppercase:
Property not set:
=> feat: adding optional uppercase to tabs

src/components/dialog/Dialog.mdx, src/components/dialog/Dialog.test.tsx, src/components/dialog/DialogContent.tsx, src/components/dialog/__snapshots__/Dialog.test.tsx.snap
Currently, it is not possible to manipulate the close button in the modal. Adding a prop to `DialogContent` to make it possible. Snapshots in PR for reference
=> feat: make it possible to show / hide close button in modal

src/components/slider-field/SliderField.mdx, src/components/slider-field/SliderField.test.tsx, src/components/slider-field/SliderField.tsx, src/components/slider-field/__snapshots__/SliderField.test.tsx.snap, src/components/slider/Slider.mdx, src/components/slider/Slider.test.tsx, src/components/slider/Slider.tsx, src/components/slider/SliderSteps.tsx, src/components/slider/SliderValue.tsx, src/components/slider/__snapshots__/Slider.test.tsx.snap
I needed a slider value label for work on the main site and realised that a slider is the only form component that doesn't explicitly state what its value is. I believe this isn't great as all inputs should probably inform the user of what input they're making. So I played around a bit and made this.
Works with the slider steps, has custom empty state, supports custom value placement and pluralisation. There's also simple use case as well with default values so you can simply pass `showValue` to the slider and it will work.
=> feat: slider value label

src/components/calendar/__snapshots__/Calendar.test.tsx.snap, src/components/date-field/__snapshots__/DateField.test.tsx.snap, src/components/field-wrapper/__snapshots__/FieldWrapper.test.tsx.snap, src/components/input-field/__snapshots__/InputField.test.tsx.snap, src/components/link/__snapshots__/Link.test.tsx.snap, src/components/markdown-content/__snapshots__/MarkdownContent.test.tsx.snap, src/components/slider-field/__snapshots__/SliderField.test.tsx.snap, src/components/slider/__snapshots__/Slider.test.tsx.snap, src/components/stack-content/__snapshots__/StackContent.test.tsx.snap, src/components/text/Text.tsx, src/components/text/__snapshots__/Text.test.tsx.snap, src/components/validation-error/__snapshots__/ValidationError.test.tsx.snap
When nesting `<Text />` elements, it would always render the nested component on a new line, including spacing set on the `<Text />` element. This is usually not what you want when you nest `<Text />` elements, as the most common cases are with using inline HTML elements such as `span`, `strong`, `em`, etc.
```tsx
<Text>This is text, <Text as="strong">and more text</Text></Text>
```
=> feat: remove :before and :after for nested Text components

src/components/date-input/DateInput.tsx
Noticed a tiny bug on the DateInput (that for some reason doesn't show up in the sandbox) - `onDateSelected` was being set as a required prop on DateInput even though it's not used as a prop and is set explicitly within DateInput on the Calendar component. So I have used `Omit` to remove that key from `DayzedInterface` when it is used to construct DateInput's prop types.
=> fix: dateinput type error

src/components/date-field/DateField.tsx, src/components/date-input/DateInput.mdx, src/components/date-input/DateInput.test.tsx, src/components/date-input/DateInput.tsx
Description
The `DateInput` wasn't taking any external change handlers, so if you needed to do something with the set value, there was no reliable way. This adds an optional `handleChange` prop to the component, which gets called inside the `onDateSelected` callback.
=> fix: allow external change handler on date input

src/components/button/Button.mdx, src/components/button/Button.tsx
In the parent portal we have a lot of white buttons that are currently not handled by theme. As such, there is inconsistency between their active and hover states because different people have added them at different times. We would like to consolidate this use case into a new button theme, Neutral.
https://user-images.githubusercontent.com/66493855/154307177-23a43508-6a19-45b5-ad55-5e6230f1dab4.mov
Outline variant:
=> feat: button neutral theme

.github/workflows/auto-fix.yml
Added a new "Autofix" workflow to run ESLint and Prettier on merge into `main`, the commit will appear as "Apply auto-fix changes" co-authored by a Github actions user and the PR (or last commit) author
=> Chore: add new action to lint and format on merge into main

src/components/stepper/StepperStepBack.tsx, src/components/stepper/StepperStepForward.tsx, src/components/stepper/types.ts
With the initial release, the Stepper component's types had the `StepNext` and `StepForward` require a `label` prop, which is actually optional. Also, because we pull in the `Button` component's props, `children` was also required, when in fact it's optional.
=> Fix stepper types

src/components/grid/Grid.mdx, src/components/grid/Grid.tsx
When using the grid earlier I noticed that you can't set a max item size. Because of the way the component is composed setting css `gridTemplateColumns` manually is impossible, and we hardcode the max size of the `minmax` function. I know. a lot of use cases want it to be `1fr`, but I needed the option earlier and didn't have it, so have added `maxItemSize` as an optional prop. 
With maxItemSize:
Without maxItemSize:
=> feat: grid max item size

src/components/stepper/Stepper.mdx, src/components/stepper/Stepper.test.tsx, src/components/stepper/StepperSteps.tsx, src/components/stepper/__snapshots__/Stepper.test.tsx.snap
Adjusted the colours of the separator lines and also the step skipping behaviour: 
* the user can only skip to a step if they previously viewed it
* the separator line will remain dark blue even if the user goes back to previous steps, as long as the bullet after it has been viewed
https://user-images.githubusercontent.com/9009155/156189838-a041d3a2-ee6b-4116-827b-65407351072d.mov
=> fix: separator colours and skipping behaviour

src/components/stepper/Stepper.mdx, src/components/stepper/StepperSteps.tsx, src/components/stepper/__snapshots__/Stepper.test.tsx.snap, src/components/stepper/types.ts
By default, the Stepper.Steps component had all the spacing and dimensions hardcoded, meaning that if you had a small number of bullets on a large screen, these would gather to center of the screen, leaving a lot of empty space between them and the Back/Next buttons. 
We needed a way to make the container's width dynamic and also make sure the separator lines between bullets are spaced and sized accordingly.
Screenshots:
Before:
After:
=> Add ability to customize the StepperSteps container css

src/components/button/Button.mdx, src/components/button/Button.test.tsx, src/components/button/Button.tsx, src/components/button/__snapshots__/Button.test.tsx.snap
Problem: 
```tsx
<Button theme="secondary" appearance="outline">Button</Button>
```
The above rendered a button with `color: rgb(0,0,0)` when it should have rendered one with `color: $primaryDark`
Reason: 
Compound Variant for this combination was absent. Hence it was falling back to default color
Fix: 
Adds a compound variant to remedy that
Preview :
https://user-images.githubusercontent.com/1936119/160368094-fe8cedb3-9aa3-4416-a491-93dbd9f09048.mov
=> fix: add compound variant for outline secondary buttons

src/components/stepper/Stepper.mdx, src/components/stepper/Stepper.test.tsx, src/components/stepper/StepperStepForward.tsx, src/components/stepper/types.ts
JIRA: https://atomlearningltd.atlassian.net/browse/PP-160
Adding the ability to override the default `StepForward` click behaviour by passing a onClick function.
This will be useful when we need to add some logic or validation before moving to the next step or we want to prevent moving to the next step if something goes wrong.
=> feat(stepper): adding ability to override default forward behaviour

src/components/file-input/FileInput.tsx, src/components/file-input/__snapshots__/FileInput.test.tsx.snap
Description
The FileInput uses the wrong icon alongside the button label (Download instead of Upload). Also, because the actual `input type="file"` is  currently the first nested child of the wrapping `Button`, making the `icon` the second child, the margin applied to the `icon` is to the left, instead of right , as we need it to be.
Screenshots:
Before:
After:
=> fix: file input using wrong icon

.github/workflows/auto-fix.yml
My previous attempt at setting up an automatic lint/formatting step tried to use the bot's access token in the wrong step: we have to use it at the checkout step!
=> fix: bot token in correct workflow step

src/components/file-input/FileInput.test.tsx, src/components/file-input/FileInput.tsx
Description:
The onSelect prop that the FileInput accepts conflicts with the React onSelect event, so when trying to pass a typed function, TS throws an error.
=> fix: onSelect prop name clashing with the built-in React onSelect event

src/components/dialog/DialogContent.tsx, src/components/dialog/__snapshots__/Dialog.test.tsx.snap
After bumping Radix Dialog version to 0.1.2 the Dialog component was being rendered behind some components
Related PR: https://github.com/Atom-Learning/components/pull/322
- Wrapping dialog into a Portal
- Setting z-index to dialog overlay and content
- Wrapping the dialog content into the overlay to allow scrolling
=> fix: setting modal content and overlay z-index so it appears correctly on top of other components

src/components/radio-button-field/RadioButtonField.mdx, src/components/radio-button-field/RadioButtonField.test.tsx, src/components/radio-button-field/RadioButtonField.tsx
`RadioButtonField` does not expose a way of knowing when the value changes, it thus requires `watching` the form field to know when the value changes and then doing something. This PR adds an optional `onValueChange(value: string)` prop that will get called when a value in the radio group gets changed, allowing the caller to do something with that value.
=> fix: allow on change handler in radio button field

src/components/dialog/DialogContent.tsx, src/components/dialog/__snapshots__/Dialog.test.tsx.snap
We have had issues on core with dialogs getting too tall for screen. Given we assume a max width, I suggest we assume a max height and allow Y axis scrolling.
- added `maxHeight` and `overflowY` properties
- updated snapshots
Dialog with really big blue box, scrolls when necessary:
=> feat: dialog max height

src/components/form/Form.mdx, src/components/form/Form.test.tsx, src/components/form/Form.tsx, src/components/form/Form.types.ts
Added optional onError callback prop that can be passed to Form component. React hook form passes both onError and onSubmit callback to handleSubmit function and calls onSubmit if there are no errors and onError instead if any errors are present.
=> feat(form): added optional onError callback to handleSubmit

src/components/table/Table.mdx, src/components/table/TableBody.tsx, src/components/table/TableCell.tsx, src/components/table/TableHeader.tsx, src/components/table/__snapshots__/Table.test.tsx.snap
I needed a light theme for the table component, where we have a grey header and no alternating row colours.
https://atomlearningltd.atlassian.net/jira/software/projects/PAR/boards/11?selectedIssue=PAR-126
- Added `light` theme to `Table.Header`
- Extended `Table.Body` to accept a striped prop, which is a boolean.
- Removed the alternating background colour from `Table.Cell` so it can be handled at a `Table.Body` level
- Updated snapshots and mdx
=> feat: table theme light

src/components/grid/Grid.tsx
The `<Grid />` component outputs the following line of CSS by default:
```ts
gridTemplateColumns: `repeat(auto-fit, minmax(${minItemSize}, ${maxItemSize}))`
```
`maxItemSize` is optional and defaults to `1fr`, but `minItemSize` is required. `auto-fit` only works with fixed values, so this means that we cannot create a grid with flexible column widths at the moment.
Because we cannot override the `gridTemplateColumns` property either, we can't opt-out of using `repeat` and `auto-fit`.
- Make `minItemSize` optional and only set `gridTemplateColumns` when it is defined.
- Move the `css` spread to the end of the object, so that the `gridTemplateColumns` property can always be overridden.
Checked the `core` codebase, and it doesn't conflict anywhere.
=> feat: made the minItemSize prop optional and allow gridTemplateColumns property to be overridden

src/components/tabs/TabsTriggerList.tsx
I noticed that `Tabs.TriggerList` wasn't doing anything when `appearance="uppercase"` was passed in.
In order to stop the textTransform property being overridden, I set the CSS from the uppercase variant to apply to descendant buttons instead of on the object itself.
=> fix: tab triggerlist uppercase

src/components/table/TableRow.tsx, src/components/table/__snapshots__/Table.test.tsx.snap
Using the striped variation of the `Table` component with cells wrapped by other elements was applying the striped background colour to the cells. This happens  because the TableRow was being created without any styles and Stitches was applying the background to any odd/even child element in the `tbody`.
Before:
After:
=> fix: table row striped layout

src/components/select/Select.tsx
From https://github.com/Atom-Learning/components/issues/306
Our select components were causing a console warning when they were controlled, due to the way they were composed. I have fixed this.
Conditionally pass in `value` and `defaultValue` in order to only have one on the object, so the component can be either controlled or uncontrolled.
=> fix: select controlled warning

src/components/dialog/Dialog.mdx, src/components/dialog/Dialog.test.tsx, src/components/dialog/Dialog.tsx, src/components/dialog/DialogBackground.tsx, src/components/dialog/DialogContent.tsx, src/components/dialog/__snapshots__/Dialog.test.tsx.snap
The `Dialog` component has a predefined background / overlay, as of now. This PR will allow us to set custom background (components / images), which will be placed above `Overlay` and under `DialogContent`
[Slack Thread](https://atom-learning.slack.com/archives/G01G926F9DM/p1656334232053669?thread_ts=1656330160.946999&cid=G01G926F9DM)
```tsx
<Dialog>
<Dialog.Trigger asChild>
<Button>Open Dialog</Button>
</Dialog.Trigger>
<Dialog.Content>
<Dialog.Background css={{ backgroundImage: 'url(https://img.freepik.com/free-vector/hand-painted-watercolor-abstract-watercolor-background_23-2149005675.jpg?t=st=1656407416~exp=1656408016~hmac=1016624970b6b9e73d8245819f3657f0d7948d053eb886fe5c1355b8882d7e74&w=1800)' }}>
Hello
</Dialog.Background>
<Heading size="sm" css={{ mb: '$3' }}>
Dialog
</Heading> …
```
=> Feat: Dialog - Custom Background

src/components/button/Button.tsx
Currently the button component will be full width in both mobile view and non-mobile view when using `fullWidth={{ '@initial': true, '@sm': false }}` with this change it will only be full width in mobile view.
A little bit of context:
https://www.figma.com/file/j1Xz1sJfHoSFVcCCZXn4Tc/Comprehension-Uploader?node-id=1099%3A15584
=> Setting false fullWidth value on Button

src/components/dialog/DialogContent.tsx
We have started seeing some failing tests which have been traced to the changes introduced in `v1.17.0`
```
TypeError: Cannot read property 'type' of null
at /Users/avinah/workspace/atom-core/.yarn/__virtual__/@atom-learning-components-virtual-a3a313397e/0/cache/@atom-learning-components-npm-1.17.0-c6922d29f2-c0ffecf250.zip/node_modules/@atom-learning/components/dist/index.cjs.js:1:30825
```
Adding a null check in attempt to fix it
=> Fix: DialogContent - handle case where child can be null

lib/src/components/search-input/SearchInput.tsx
Issue raised on DS jira board https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-90
The SearchInput wasn't properly clearing when functioning in a controlled manner. For example, if you did
`<SearchInput value={value} onChange={(e) => setValue(e.currentTarget.value)} />`
that wouldn't trigger when you press the internal clear button of the SearchInput.
Because in a controlled manner the SearchInput doesn't internally have access to the setState function for the value it is displaying, the state would not update when the internal value is cleared. We use `onChange` to send those changes up to the setState, but clearing using the button isn't the same as changing and it doesn't call the native change events.
To solve this, we access the native event …
=> fix: search input clear

lib/src/components/button/Button.tsx
`fullWidth = {false}` currently sets the `Button`'s `width` to `auto`, but we default it to `max-content` when no `fullWidth` prop is provided, so we should revert back to that when `fullWidth` is `false`. 
Since the `Button` has `display: flex`, `width: auto` forces it to take up all available horizontal space, so it might as well have `width: 100%`! 🤦🏻
=> Fix: Button fullWidth false variant

lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap, lib/src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap, lib/src/components/button/__snapshots__/Button.test.tsx.snap, lib/src/components/calendar/__snapshots__/Calendar.test.tsx.snap, lib/src/components/carousel/__snapshots__/Carousel.test.tsx.snap, lib/src/components/date-field/__snapshots__/DateField.test.tsx.snap, lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap, lib/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, lib/src/components/field-wrapper/__snapshots__/FieldWrapper.test.tsx.snap, lib/src/components/file-input/__snapshots__/FileInput.test.tsx.snap, lib/src/components/icon/Icon.tsx, lib/src/components/icon/__snapshots__/Icon.test.tsx.snap, lib/src/components/input-field/__snapshots__/InputField.test.tsx.snap, lib/src/components/notification-badge/__snapshots__/NotificationBadge.test.tsx.snap, lib/src/components/password-field/__snapshots__/PasswordField.test.tsx.snap, lib/src/components/password-input/__snapshots__/PasswordInput.test.tsx.snap, lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap, lib/src/components/stepper/__snapshots__/Stepper.test.tsx.snap, lib/src/components/toggle-group/__snapshots__/ToggleGroup.test.tsx.snap, lib/src/components/validation-error/__snapshots__/ValidationError.test.tsx.snap
The existing stroke-width values for our icons was a little high, making some icons difficult to read in small sizes.
Jira ticket: https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-103
Some examples running in the docs site locally:
=> Fix: update stroke widths for icons

lib/src/components/toggle-group/ToggleGroup.mdx, lib/src/components/toggle-group/ToggleGroup.test.tsx, lib/src/components/toggle-group/ToggleGroupButton.tsx, lib/src/components/toggle-group/ToggleGroupRoot.tsx, lib/src/index.ts
Some small-ish changes to the design system which arose while I was working on https://github.com/Atom-Learning/atom-core/pull/2129
[feat: focusVisibleStyleBlock export](https://github.com/Atom-Learning/components/pull/371/commits/fd50c4ca6576da0c6459fb765e6edfca5db2fc28)
^ I need this to do the focus style around a Sortable Button in core
[refactor: ToggleGroup simplify and forwardRef](https://github.com/Atom-Learning/components/pull/371/commits/16cd33cc20688e3dd750dafb1c84afbf4374e6f0)
^ I've done the same pattern in sortable when I use a size but I've done it per child (like this change suggests) rather than cloneElement.
I honestly think it's much simpler and probs efficient to just pass the prop when needed rather than give to parent and clone so I want to change ToggleGroup to work …
=> Gt 178 drag and drop design system changes

lib/src/components/date-input/use-date.ts
Previous behaviour:
>have date field set to dateFormat=DD/MM/YYYY
>we’re converting to YYYY-MM-DD
>if I go 25/10/2015 it outputs 2015-10-25
>if I go 10/25/2015 rather than saying invalid it outputs 2017-01-10
https://day.js.org/docs/en/parse/is-valid
=> Fix: DateField accepting invalid date

lib/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, lib/src/constants/dialog.ts
The `z-index` value of the reCAPTURE image challenge is `2000000000` - which is less than the current z-index of our dialogs thus gets hidden behind our dialogs and prohibits signups. This [PR](https://github.com/Atom-Learning/atom-core/pull/2165) attempted to override the z-index of the reCAPTURE image challenge, however, the [solution wont work on Chrome](https://caniuse.com/css-has). @Mhoog and I tried a few other CSS selections, but there is no "safe" solution we can use without the worry that something in the DOM might change and without using `:has`
=> Fix: Reduce dialog z-index value

lib/src/components/calendar/Calendar.test.tsx, lib/src/components/calendar/Calendar.tsx, lib/src/components/calendar/__snapshots__/Calendar.test.tsx.snap, lib/src/components/calendar/constants.ts, lib/src/components/date-input/DateInput.tsx
As we have added the date input for DOB on the new signup flow in core, we wanted to add a year selector to the calendar. You can now click on the year when viewing the calendar, and you'll be shown a grid of years you can click on and scroll through with the arrows. Clicking a year sets the year for the current set date but keeps the day and month, and takes you back to the calendar screen.
This year grid is constrained within the minDate and maxDate values (if set), so you can't use it to set a date you otherwise wouldn't be able to set.
=> feat: calendar year picker

lib/src/components/checkbox/Checkbox.mdx, site/src/sandbox/components.tsx
The indeterminate state for checkboxes is already available in the design system however there’s no documentation that mentions that in the DS. This PR adds an example to the checkbox component page and the larger component page.
https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-109
=> Add checkbox indeterminate state example to docs

lib/src/components/top-bar/TopBar.mdx, lib/src/components/top-bar/TopBar.test.tsx, lib/src/components/top-bar/TopBar.tsx, lib/src/components/top-bar/TopBarBrand.tsx, lib/src/components/top-bar/__snapshots__/TopBar.test.tsx.snap
Ticket: https://atomlearningltd.atlassian.net/browse/DS-129
**This PR is blocking this task** https://atomlearningltd.atlassian.net/jira/software/projects/STU/boards/1?selectedIssue=STU-729 as we need to make the changes to the DS Component before we can use the Component locally in the Student App.
From our discussion with @avirati  @hollg  @andoulla and @MiguelGDLR  we needed to allow the option to increase the height of the `TopBar` Component so it would be easier for the Student Pod to use and customise the `Topbar` to their specific needs. This was done by implementing a size variant for the `TopBar`, following these designs https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=2973%3A5433
During my discussion with @hollg he suggested the ideal solution would be …
=> fix(TopBar): add size variant

lib/src/components/checkbox-field/CheckboxField.tsx, lib/src/components/date-field/DateField.tsx, lib/src/components/field-wrapper/FieldWrapper.tsx, lib/src/components/field-wrapper/index.ts, lib/src/components/input-field/InputField.tsx, lib/src/components/password-field/PasswordField.tsx, lib/src/components/radio-button-field/RadioButtonField.tsx, lib/src/components/search-field/SearchField.tsx, lib/src/components/search-input/SearchInput.tsx, lib/src/components/select-field/SelectField.tsx, lib/src/components/slider-field/SliderField.tsx, lib/src/components/textarea-field/TextareaField.tsx
When using `<TextareaField />` or `<SelectField />` components TS complains saying that the `fieldId` prop is required because their component props extend from `FieldWrapperProps`, but when you add the prop we get a warning in the console: `React does not recognize the 'fieldId' prop on a DOM element.`. In https://github.com/Atom-Learning/components/commit/ee8f9ad66f74e26c047b37c5436e27a329e2ff47 I omit `fieldId` from the props, however in e0b149a29507720f31f69930b384c014c3af3cc9 I created a type that we can use for field elements that are wrapped with `FieldWrapper` in order to not repeat the type and keep it consistent.
=> Fix: field element prop warnings for `fieldId`

lib/src/components/date-field/__snapshots__/DateField.test.tsx.snap, lib/src/components/date-input/DateInput.tsx, lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap
When rendering a `DateInput` within a `Dialog`, the `Popover` thats rendered when you click "Open calender" gets cut off within the `Dialog` as it overflows the content area. This update wraps the `Popover` in a `Portal` to allow it to correctly render outside of the bounds of the containing `Dialog`, and also adds a higher z-index to ensure it renders on top of the parent dialog.
Unfortunately, I couldn't add a test for this behaviour as it relies on `toBeVisible` to recognise the bounding box of the `Dialog` and the pixels that are overflowing https://github.com/testing-library/jest-dom#tobevisible
=> fix: add portal and zindex to date-input

lib/src/components/data-table/DataTable.test.tsx, lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/number-input-field/__snapshots__/NumberInputField.test.tsx.snap, lib/src/components/number-input/__snapshots__/NumberInput.test.tsx.snap, lib/src/components/tooltip/TooltipContent.tsx, lib/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
Before the fix, if the tooltip was used inside a table header with the style `white-space: nowrap` it would inherit that style for the tooltip content and would make the test be one line and overflow the tooltip if the text was larger than the tooltip width
[Jira Ticket](https://atomlearningltd.atlassian.net/browse/POG-286)
Screenshots broken and fixed:
=> fix(tooltip): override white-space style to make sure the text inside always wraps

lib/src/components/stepper/Stepper.mdx, lib/src/components/stepper/Stepper.test.tsx, lib/src/components/stepper/Stepper.tsx, lib/src/components/stepper/StepperStepBullet.tsx, lib/src/components/stepper/StepperStepContainer.tsx, lib/src/components/stepper/StepperSteps.tsx, lib/src/components/stepper/__snapshots__/Stepper.test.tsx.snap, lib/src/components/stepper/stepper-context/StepperContext.tsx, lib/src/components/stepper/types.ts
https://atomlearningltd.atlassian.net/browse/DS-143
Note: part of that ticket requires a change on core once this work has been done and DS version on core updated
This fixes a number of issues with the stepper component and the various states that is has:
- The stepper track was not correctly showing as blue for completed items, this has been fixed
- Viewed (but not completed) items now show a darker than normal colour to separate them from default state
- Added a prop to allow showing tick icons for completed steps instead of their step number
- Changed the default state colour to be slightly darker so it shows up better on light backgrounds
- Moved the interaction states (hover, focus) to only appear when allow skip prop is present, this is because otherwise there would be no …
=> fix stepper state updates

lib/src/components/navigation/NavigationMenuItem.tsx, lib/src/components/navigation/__snapshots__/NavigationMenu.test.tsx.snap
I found really weird issue with elements not fitting in the dropdown content area.
I played with it and noticed that `unset: all` makes this problem.
https://user-images.githubusercontent.com/23363033/201041512-f2a63f84-3e1d-40dd-9086-0aa2ec10d439.mov
=> fix: navigation-menu list rendering issue

lib/src/components/navigation/NavigationMenu.mdx
We were missing `>` sing in mdx file.
=> fix: navigation-menu mdx missing sign

lib/src/components/link/Link.tsx
We were stripping the `onClick` prop when we rendered an `a` in `Link`.
In the main repo, we had several `Link` implementations with both an `href` and `onClick`. Because we had a wrapper component that rendered this `Link` component as a `react-router` `Link`, the `onClick` would still be fired (this component would render a `button` that would then be rendered as a `react-router` `Link` that rendered an `a`, retaining both the `href` and `onClick`.
_(kudos if you're still following me)_
To make sure `noCapsize` was only applied to `button` links, we had to make a change to this wrapper and make sure it rendered an `a` straight away when creating an internal link. This broke links with both `onClick` and `href` as we strip `onClick` in this `Link` component.
- Pass on `onClick` to both …
=> feat: pass onClick prop onto anchor links

lib/src/components/data-table/DataTable.mdx, lib/src/components/data-table/DataTableContext.tsx
Problem: paginated `DataTable`s render all of their rows on the initial render, not just the first page. So if any heavy-lifting happens in a row (e.g. API requests are made) then a big table can cause a browser crash.
Cause: `DataTable.Pagination` tells `DataTable` to paginate its data in a `useEffect`. `useEffect` fires after the render.
Short-term solution (this PR): Add an optional `pagination` prop to `DataTable` which will set pagination state for the first render
Long-term solution: overhaul the API
=> fix: workaround to only render first page of rows

lib/src/components/divider/Divider.tsx, lib/src/components/divider/__snapshots__/Divider.test.tsx.snap, lib/src/components/markdown-content/__snapshots__/MarkdownContent.test.tsx.snap, lib/src/components/stack-content/__snapshots__/StackContent.test.tsx.snap, lib/src/components/top-bar/__snapshots__/TopBar.test.tsx.snap
Ticket https://atomlearningltd.atlassian.net/browse/DS-145
- Updated background colour to `$tonal100` 
Old and new colours for comparison
=> chore: updated divider colour

lib/src/components/sidedrawer/SidedrawerClose.tsx
`Sidedrawer.Close` customization
We found a need in Parent app to increase the size of `Sidedrawer.Close`.
Instead of changing the fixed `size` in design system, I made a solution with set of customisable props.
It's more flexible so other pods might align the Close for their needs.
It still keep the default values, so we have initial settings out of the box.
=> feat: sidedrawer close customizable

lib/src/components/avatar/Avatar.mdx, lib/src/components/chip-dismissible-group/ChipDismissibleGroup.mdx, lib/src/components/chip-toggle-group/ChipToggleGroup.mdx, lib/src/components/dismissible-group/DismissibleGroup.mdx, lib/src/components/dismissible/Dismissible.mdx, lib/src/components/tabs/Tabs.mdx, lib/src/components/toast/Toast.mdx, lib/src/components/toggle-group/ToggleGroup.mdx, site/src/components/PropsTable.tsx
Some components were not showing any API reference section
[Jira Ticket](https://atomlearningltd.atlassian.net/browse/FG-223)
`lib/scripts/generate-component-props.mjs` is responsible for generating a `docgen.json` file. This file is used by the component `<PropsTable.tsx>` to display the API reference. The components which API reference it will show are taken from the first section of the corresponding `.mdx` file.
For instance, in the `Avatar.mdx` file we have this:
```
---
title: Avatar
component: Avatar,Avatar.Image,Avatar.Initial,Avatar.Placeholder,Avatar.Icon
description: Show a thumbnail representation of an individual or entity.
category: Media
---
```
So `<PropsTable.tsx>` will try to show an API reference for each component of that list. But it actually, doesn't know to go into …
=> fix: show missing API references

lib/package.json, lib/src/components/data-table/DataTable.mdx, lib/src/components/data-table/DataTable.test.tsx, lib/src/components/data-table/DataTableContext.tsx, lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, yarn.lock
There are two issues that this PR addresses:
- The internal data array is not updated when new data is passed in.
- If the data is being manipulated outside of the table (such as filtering) the data is passed back into the component. I believe we need to maintain this flexibility.
- Unable to retrieve the pagination state using `useDataTable` from the FE implementation of DataTable
- Since we provide a managed pagination state, onPaginationChange and a page count to`useReactTable` we need to ensure our `paginationState` is not undefined.
- Adds a `useEffect` which will update the internal data state when the data prop changes
- Defaults the pagination state for both `getAsyncData` & `dataProp` implementations
=> Feat: Datatable FE pagination state

README.md, lib/src/components/list/List.test.tsx, lib/src/components/list/List.tsx, lib/src/components/list/__snapshots__/List.test.tsx.snap, package.json
This PR re-introduces the theme variant for the list component, as we need it for the DS migration of the list https://atomlearningltd.atlassian.net/browse/FG-197. I have only added the primary variant since this is what we need only now.
https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-283
=> Fix: broken list theme variant

lib/src/components/data-table/drag-and-drop/DragAndDropContainer.tsx, lib/src/components/data-table/drag-and-drop/DraggableRow.tsx, lib/src/components/data-table/drag-and-drop/index.ts
Fixes a problem where custom `idColumn` values didn't work correctly.
My original drag-and-drop row implementation had a bug where `DraggableRow` assumed the consumer was providing IDs for each row in an `id` property and `DragAndDropContainer` tried to read the id `@dnd-kit/sortable` provided dynamically using the `idColumn` value. This was the wrong way round!
Instead, `DraggableRow` now uses the provided `idColumn` find the value to provide as `@dnd-kit/sortable`'s `id` and `DragAndDropContainer` correctly reads the `id` from the objects that come out of `@dnd-kit/sortable`.
=> Fix: read DataTable custom idColumn correctly

lib/src/components/navigation/NavigationMenuDropdownContent.tsx, lib/src/components/navigation/NavigationMenuDropdownTrigger.tsx, lib/src/components/navigation/preventHover.ts
Jira: https://atomlearningltd.atlassian.net/browse/DS-165
Requirement: Have the navigation menu dropdown open only on click and not on hover.
Solution: https://github.com/radix-ui/primitives/issues/1630
https://user-images.githubusercontent.com/6905473/214565843-ca1e4113-5b36-43df-a7d9-978fdaa572d2.mov
=> feat: do not open NavigationMenuDropdown via pointer events

lib/package.json, lib/src/components/alert-dialog/AlertDialogContent.tsx, lib/src/components/dialog/DialogContent.tsx, lib/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, lib/src/stitches.ts, site/package.json, yarn.lock
Updating `@stitches/react` to fix a number of issues with the library with later versions of Typescript.
@Mhoog and I have been through the wringer over the past few weeks trying to resolve some type issues with `@atom-learning/components` and `@stitches` in particular, resulting in this need to update `@stitches` to the latest published version (a beta).
I've written some of the steps that we went through to provide a bit of context, but it included a fair amount of trial and error testing, patching local versions of the packages, whilst also trying to resolve local TS issues with our codebase, so please let me know if you want any more detail on why we did certain things, but hopefully, we concluded with a relatively simple fix.
The initial issue we hit was with how `@stitches` accessed …
=> Chore: Update `@stitches/react`

lib/src/components/radio-button-field/RadioButtonField.mdx, lib/src/components/radio-button-field/RadioButtonField.tsx
RadioButtonField (Radio group) currently doesn't allow to be controlled. This causes bugs when trying to use it with `onValueChange` in core.
Other Field components do allow for the value to be controlled so this PR is to allow it fro RadioButtonField as well.
**eg. SelectField (allows for value controlling)**
https://user-images.githubusercontent.com/6905473/216050826-06d45412-c5c6-4b51-90e4-ff637f78a808.mov
**before**
https://user-images.githubusercontent.com/6905473/216050958-8420ae71-c84b-4836-8ace-5d5ef5a1e9f4.mov
**after**
https://user-images.githubusercontent.com/6905473/216051013-713a4e78-fc1e-4b7d-aae7-3485a7af6b64.mov
=> feat: RadioButtonField allow controlled value

lib/src/components/data-table/DataTableGlobalFilter.tsx, lib/src/components/search-input/SearchInput.test.tsx, lib/src/components/search-input/SearchInput.tsx, lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
**BREAKING CHANGE: will need to change all uses of `value` to `defaultValue` in core or use controlled version**
> SearchInput component is uncontrolled. The value prop only acts as defaultValue setting the initial state of inner component state and not being used after that.
This PR allow for use both with a defaultValue (uncontrolled) and value (controlled).
JIRA: https://atomlearningltd.atlassian.net/browse/DS-308
**With this sandbox:**
**before:**
https://user-images.githubusercontent.com/6905473/218333054-9badc578-a598-4cf0-99b7-6b7cb3e465d1.mov
**after:**
https://user-images.githubusercontent.com/6905473/218332838-67fa72c4-8dd3-44e6-9c7b-91a92011862a.mov
=> feat: allow SearchInput to be both controlled and uncontrolled

documentation/package.json, lib/package.json, lib/src/utilities/create-theme-variants/createThemeVariants.test.ts, yarn.lock
Updates the `@atom-learning/theme` dependency to `v1.2.0`, which includes:
* New purple colour scale
* Updated internal naming for blue and grey scales
* Aliases to prevent the public API for the blue and grey scales from changing for now (this means no broken snapshots here!)
* Temporary `$24` space token to smooth the eventual process of adding a `24px` value in that scale
=> Feat/theme v1.2.0

lib/src/components/checkbox-field/CheckboxField.tsx
> If you pass anything into onCheckedChange prop on the CheckBoxField component, nothing happens.
JIRA: https://atomlearningltd.atlassian.net/browse/DS-333
With this sandbox:
**before**
https://user-images.githubusercontent.com/6905473/222427987-098508ea-aac3-4e83-8542-38a08c69c71b.mov
**after**
https://user-images.githubusercontent.com/6905473/222428011-b58da920-be09-40c6-980d-3ba94866e6f6.mov
=> feat: keep onCheckedChange prop usable in CheckboxField

lib/src/components/field-wrapper/FieldWrapper.test.tsx, lib/src/components/field-wrapper/FieldWrapper.tsx
This change allows the `FieldWrapper prompt` to have an `onClick` instead of just a link. This allows for the edge case where we need to trigger an action from the prompt that isn't a redirect.
The component looks exactly the same, and the prompt still will look like a link. 
This is needed to unblock https://atomlearningltd.atlassian.net/browse/FG-237.
=> fix(fieldwrapper): allow prompt to have an onClick

documentation/README.md, documentation/content/components.content.table.md, lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/table/Table.test.tsx, lib/src/components/table/Table.tsx, lib/src/components/table/TableCell.tsx, lib/src/components/table/TableFooterCell.tsx, lib/src/components/table/TableHeaderCell.tsx, lib/src/components/table/__snapshots__/Table.test.tsx.snap
JIRA ticket
The `xl` size is a bit bigger than the `lg`. Initially, we were going to call it `lg` and move the 2 existing sizes (`md` and `lg`) 1 level down. But we did it this way to be the least disruptive possible to the current usages.
This PR also makes the vertical padding depending on the `size`. Otherwise, tables with different sizes could actually look the same, as the row height which is the only thing the size was affecting is just a minimum, it can grow with taller content.
=> Ds 73/add table xl size

documentation/public/admin/config.yml
Enables the `publish_mode: editorial_workflow` in the CMS, [as described here](https://decapcms.org/docs/add-to-your-site/#editorial-workflow).
Totally empty Jira ticket: https://atomlearningltd.atlassian.net/browse/DS-337
This allows us to draft content without publishing it. Draft content will be opened as a PR against the `documentation-content` branch. Approving a draft in the CMS will merge that PR. The existing GitHub Actions workflows should handle the rest, syncing `main` with the update to `documentation-content`, triggering a new deployment on Digital Ocean.
Note: as far as I can tell, there's no way to test this locally, since the CMS running on my machine can't authenticate with GitHub and if I switch to `local_backend` then there's nothing to PR against. So we'll have to test …
=> feat: enable editorial workflow

documentation/components/markdown/editor-component/DosAndDonts.tsx, lib/src/components/grid/Grid.tsx
Self explanatory.
Had to specify `as` for Grid as typescript was throwing - copied exactly how Stack does it.
=> fix: typescript errors to make build:docs happy again

documentation/components/page/Layout.tsx, documentation/pages/[...slug].tsx
[JIRA](https://atomlearningltd.atlassian.net/browse/DS-346)
When navigating from a component tab that was not the first tab to a component that only has one tab an empty screen was shown. This has been fixed
The problem is that the current tab was stored in the tab provider, and was not reset when navigating from one component to other.
~Going from un uncontrolled approach to a controlled approach for the tabs and resetting it when the `slug` changes did the trick.~
After some review comments, I tried usin `key={slug}` so the tabs re-render. It doesn't work in the `<Tab>` component directly, so I did it in the parent component.
https://user-images.githubusercontent.com/4931116/231988038-dff1abd6-3d19-4f08-981d-023c63d68d91.mov
https://user-images.githubusercontent.com/4931116/231988085-3bf …
=> fix: empty page when navigating from a tab that is not the first

documentation/content/components.feedback.section-message.md, lib/src/components/section-message/SectionMessage.test.tsx, lib/src/components/section-message/SectionMessage.tsx, lib/src/components/section-message/SectionMessageClose.tsx, lib/src/components/section-message/SectionMessageContext.tsx, lib/src/components/section-message/SectionMessageIcon.tsx, lib/src/components/section-message/SectionMessageLayout.tsx, lib/src/components/section-message/SectionMessageText.tsx, lib/src/components/section-message/__snapshots__/SectionMessage.test.tsx.snap
Used position absolute to place `x` and `Icon` - means we can simplify top level container, and don't need a `Box` anymore.
Also we no longer need negative margins as we just position absolute exactly where we want.
Oh it also fixes title and text overflow:
=> feat: simplify SectionMessage API by utilising pos absolute

lib/src/components/checkbox-field/__snapshots__/CheckboxField.test.tsx.snap, lib/src/components/checkbox/Checkbox.tsx, lib/src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap
Checkbox has no `position: relative` - so `position: absolute` Icon glitches when nested in scrollable parent.
https://user-images.githubusercontent.com/6905473/236504880-154ebfca-c44b-4e09-bdba-76ffd93eb729.mov
add pos relative to checkbox; and since I'm there use a bit more solid css for positioning the icon and drop a div by using `asChild` for the indicator.
**BOTH BEFORE AND AFTER (1 video - notice url change)**
https://user-images.githubusercontent.com/6905473/236507988-74752674-598e-4ad4-85d0-ad4b765b9660.mov
=> fix: positioning of tick icon on Checkbox

lib/src/components/action-icon/ActionIcon.tsx
The current ActionIcon doesn't allow to have a `type=submit` when it is used as a button. By reversing the order it allows for a user to pass an override. This will make the component more flexible and allow us to use it in a form. (currently working on a field with a save action icon next to it)
**How the HTML looks like**
**Sandbox code**
=> fix(actionicon): allow overriding the button type

documentation/components/admin/editor-component/AspectRatioTokenListEditorComponent.tsx, documentation/components/markdown/editor-component/AspectRatioTokenList.tsx, documentation/components/markdown/index.tsx, documentation/content/components.feedback.section-message.md, documentation/content/components.surfaces.tile-interactive.md, documentation/content/theme.overview.aspect-ratio.md, documentation/pages/admin.jsx
[JIRA](https://atomlearningltd.atlassian.net/browse/DS-350)
The recently added aspectRatio tokens needed a component that shows the usage of the tokens in the normalised way we do the rest of the tokens that show the styling in blue boxes.
The components have been added (heavily inspired in the Shadow ones)
And they have been used in the aspect ratio page via the local CMS
=> Ds 350/aspect ratio documentation

lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/data-table/pagination/Pagination.tsx
Please ignore `NaN`, `undefined` etc in the screenshot. It's just a rushed sandbox DataTable to work with the layout.
Desktop
Mobile
=> DS 383 fix data table pagination styles so it is responsive in small screens

lib/src/components/navigation/NavigationMenu.tsx
While setting up Cypress for a11y tests, I noticed that it is not possible to pass down accessibility props to NavigationMenu. This PR fixes that
=> Chore: Pass down props to NavigationMenu

lib/src/components/pagination/PaginationItem.tsx, lib/src/components/pagination/PaginationPopover.tsx, lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap
This PR fixes two small bugs in the `Navigation` component:
1. The 'indicated page' dot was sometimes not centered horizontally in the button.
2. There was additional spacing on the right side of the popover
- Changed the way the indicated-page-dot is centered (now using `left` and `marginLeft`.
- Removed unnecessary elements around the indicated-page-dot.
- Changed the list of page numbers to use `Flex` with `gap` instead of `Stack`.
- Center aligned the page numbers, so that no extra space on the right appears when items move to the next line.
=> fix: Pagination bugs

lib/src/components/create-password-field/CreatePasswordField.tsx, lib/src/components/create-password-field/__snapshots__/CreatePasswordField.test.tsx.snap
This removes the bottom margin validation messages. I dont think it should have been added in the first place.
- It might add unwanted space below the form field
- The user should rather control how much margin (if any) should be applied. It can be applied though the css prop rather
=> fix: remove bottom margin from validation messages

lib/src/components/create-password-field/CreatePasswordField.tsx
Even though the `name` prop is defaulted, but because its still required by `PasswordInput` and the prop types extend from that it still needed to be applied.
Problem:
Fix:
=> Fix: Override create password field `name` prop to be optional

lib/src/components/chip-toggle-group/ChipToggleGroupItem.tsx, lib/src/components/chip/Chip.tsx, lib/src/components/tile-interactive/TileInteractive.tsx, lib/src/components/tile-toggle-group/TileToggleGroupItem.tsx, lib/src/components/tile/Tile.tsx
Found out during the Flex/Stack work that `asWorkaround` is not needed. Instead there is an actual workaround in stitches to ask it to not use the `as` prop and pass it through. Which works perfect for our use cases.
No visual changes.
=> feat: remove uses of asWorkaround in favour of stitches withConfig

lib/src/components/badge/stitches.badge.colorscheme.config.ts
Was just updating DS in `atom-core` and I noticed badge theme is treated as `undefined` due to empty object being picked up for it.
This change seemingly fixes this issue.
**Before**
**After**
=> fix: theme type of Badge not correct

lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap, lib/src/components/badge/__snapshots__/Badge.test.tsx.snap, lib/src/components/badge/stitches.badge.colorscheme.config.ts, lib/src/components/banner/banner-regular/__snapshots__/BannerRegular.test.tsx.snap, lib/src/components/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap, lib/src/components/tabs/__snapshots__/Tabs.test.tsx.snap, lib/src/components/tile-interactive/__snapshots__/TileInteractive.test.tsx.snap, lib/src/components/tile-toggle-group/__snapshots__/TileToggleGroup.test.tsx.snap, lib/src/components/tile/__snapshots__/Tile.test.tsx.snap, lib/src/experiments/color-scheme/stitches.colorscheme.config.ts
Spotted mistake, after a great question by @thomasdigby 
I have been naming all of the classes in all my `createTheme` uses 🤦  That's what I get for copy/pasting and not reading the docs **thoroughly**... This is obviously not great, as we end up with generic classnames like `danger`!
In this PR, I'm undoing this mistake and letting `createTheme` classes just be hashes. As they should.
**No visual changes** but defo important css changes :)
=> fix: use hashes for classes created via createTheme

lib/src/components/button/Button.tsx, lib/src/components/button/__snapshots__/Button.test.tsx.snap
When using `Button` with an `Icon` _and_ `isLoading`, the space between icon and text is not applied, this has now been fixed. While I was doing this work, I though it would help to remove the unnecessary animating state from the loader as it's currently bloating our snapshots and has little to no UX value. Also also I fixed the space between icon and text for large buttons.
=> Fix: `Button`/`Icon`/`isLoading` combo

lib/src/components/link/Link.tsx
Applied @Mhoog's polymorphic type fixes to the `Link` component (which has the same (but opposite) `a || button` style polymorphism)
=> Fix: `Link` polymorphic types

lib/src/components/pagination/PaginationPages.tsx, lib/src/components/pagination/pagination.constants.ts, lib/src/components/pagination/pagination.helper.ts
Remove hard-coded `TRUNCATED_THRESHOLD` and use `visibleElementsCount` instead
=> Fix: Pagination truncation issue

lib/src/components/button/Button.tsx, lib/src/components/link/Link.tsx
There's a sizable cold-start performance regression with the new types for `Button` and `Link`, we don't know what the cause is yet but it's pretty impactful on DX so we're temporarily reverting the change to unblocks future DS release.
=> Fix: Revert `Button`/`Link` types

lib/src/components/date-field/DateField.tsx, lib/src/components/input-field/InputField.tsx, lib/src/components/number-input-field/NumberInputField.tsx, lib/src/components/password-field/PasswordField.tsx, lib/src/components/search-field/SearchField.tsx, lib/src/components/select-field/SelectField.tsx, lib/src/components/slider-field/SliderField.tsx, lib/src/components/textarea-field/TextareaField.tsx
Fixing all inputs (form fields) that did not pass `hideLabel` prop to the FieldWrapper
`hideLabel` is passed down to the input/textarea etc. as a part of `remainingProps`.
`hideLabel` should be rather passed to the FieldWrapper.
FieldWrapper expects to receive hideLabel
Issue example: `hideLabels` is not passed down from particular form field to the FieldWrapper
Docs
Implementation images
=> fix: form inputs - hideLabel passed down to FieldWrapper

lib/src/components/data-table/DataTableHead.tsx, lib/src/components/data-table/DataTableTable.tsx, lib/src/components/table/TableHeader.tsx
This PR simply renames the `hasStickyHeader` that gets passed to the table header component into `isSticky`
=> Refactor: rename hasStickyHeader prop

lib/src/components/toast/ToastProvider.tsx
Fixes an issue with the latest update to the ToastProvider whereby once a toast was on screen, you couldn't click on anything else behind it.
- Removed `pointerEvents: 'auto'` from ToastWrapper
BEFORE:
https://github.com/Atom-Learning/components/assets/44065175/b07742bc-c28b-4e9d-9b5b-7eb3dc26b972
AFTER:
https://github.com/Atom-Learning/components/assets/44065175/11120464-8b99-4e64-abff-0f429a0939e1
=> fix: removed pointer-events auto from ToastWrapper

lib/src/components/drawer/Drawer.styles.ts, lib/src/components/drawer/DrawerClose.tsx, lib/src/components/drawer/DrawerHeader.tsx, lib/src/components/drawer/__snapshots__/Drawer.test.tsx.snap, lib/src/components/navigation-menu-vertical/NavigationMenuVertical.tsx, lib/src/components/navigation-menu-vertical/NavigationMenuVerticalAccordionTrigger.tsx, lib/src/components/navigation-menu-vertical/NavigationMenuVerticalLink.tsx, lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap, lib/src/utilities/event/preventEvent.ts
While trying to replace uses of `Sidedrawer`  with the new components I have discovered some issues.
This PR is an attempt to fix said issues and unblock the replacement a bit. 
(Might make more changes but these ones are from the first day - more important ones)
* **Major:** `as` isn't working correctly with `NavigationMenuVerticalLink`. We need it to work with this element to set a link to be a `React Router Dom` `Link` 
**before**
**after**: (in principle it works)
* **Mid**: attempt to silence Drawer.Close complaining about missing `children` prop in implementation. It doesn't accept children so changed the type to omit.
* **Minor**: Drawer paddings change and add min-height to the Header
* **Minor**: Change NavigationMenuLink and Accordion to default to use the "lg" size as per …
=> [FIXES FOR:] Ds 465 👩🏻‍💻 build navigation sidedrawer

lib/src/components/action-icon/ActionIcon.test.tsx, lib/src/components/action-icon/ActionIcon.tsx, lib/src/components/action-icon/__snapshots__/ActionIcon.test.tsx.snap, lib/src/components/button/Button.test.tsx, lib/src/components/button/Button.tsx, lib/src/components/dropdown-menu/DropdownMenu.test.tsx, lib/src/components/dropdown-menu/DropdownMenuLinkItem.tsx, lib/src/components/dropdown-menu/__snapshots__/DropdownMenu.test.tsx.snap, lib/src/components/link/Link.test.tsx, lib/src/components/link/Link.tsx, lib/src/components/navigation-menu-vertical/NavigationMenuVertical.test.tsx, lib/src/components/navigation-menu-vertical/NavigationMenuVerticalLink.tsx, lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap, lib/src/components/navigation/NavigationMenuLink.tsx, lib/src/components/navigation/__snapshots__/NavigationMenu.test.tsx.snap, lib/src/utilities/uri/index.ts
A minor fix to ensure that any component that can render a link also contains the logic to add props specific to external hrefs. e.g. `<a href="http://google.com" />` now renders as `<a href="http://google.com" target="_blank" rel="noopener noreferrer" />`
Please let me know if I've missed anything.
=> Fix: Add external link props to links

lib/src/components/alert-dialog/alert-context/AlertDialog.tsx
If you have "always show scroll" bars on mac you will see the scroll bar on the alert dialog:
**Fix:**
scroll needed
=> Fix: AlertDialog visible scroll bar

documentation/content/components.content.banner-regular.md, documentation/content/components.content.banner-slim.md, documentation/content/components.primitives.dismissible.md, lib/src/components/banner/BannerContainer.tsx, lib/src/components/banner/banner-regular/BannerRegular.test.tsx, lib/src/components/banner/banner-regular/BannerRegular.tsx, lib/src/components/banner/banner-regular/__snapshots__/BannerRegular.test.tsx.snap, lib/src/components/banner/banner-slim/BannerSlim.test.tsx, lib/src/components/banner/banner-slim/BannerSlim.tsx, lib/src/components/dismissible-group/DismissibleGroupItem.tsx, lib/src/components/dismissible/Dismissible.test.tsx, lib/src/components/dismissible/DismissibleRoot.tsx, lib/src/components/dismissible/DismissibleTrigger.tsx
A couple of tweaks to the Dismissible component:
* [as requested,](https://github.com/Atom-Learning/components/pull/600#pullrequestreview-1745767535) removes unnecessary prop of `value` from the base Dismissible
* ...but re-adds it on the DismissibleGroupItem where it actually makes sense
* allows Dismissible to be controlled: This is needed for the Banner component preview where we don't want editors to be dismissing the banner - well now with a prop we can keep it always there
* update components which use dismissible to new props setup
**No visual changes.**
=> Dismissible tweaks

documentation/content/components.table.md, lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap, lib/src/components/table/TableHeader.tsx
Table component
TableHeader themes additions
- primaryLight
- white
Ticket:  https://atomlearningltd.atlassian.net/browse/NC-442
Screenshots: 
Types improvement :)
**Before:**
- no support for themes type
**After:**
=> feat: table header themes update

lib/src/components/section-message/SectionMessageIcon.tsx, lib/src/components/section-message/SectionMessageLayout.tsx, lib/src/components/section-message/__snapshots__/SectionMessage.test.tsx.snap
SectionMessageIcon issue
SectionMessageIcon has a top edge at the same line as the content top border (top position of an icon is equal to the content padding.
Because an icon is most likely higher than the `heading`, both elements looks not aligned vertically.
There's not a perfect fix considering API shape and all of possible combinations like
- different heading size
- no heading
- no text
- heading and text 
- etc
Icon is positioned absolutely to be kept next to the `top` line of heading/text in case that heading/text is multiline.
Proposed fix:
- Add $0 padding to the content. It makes all elements more centered (icon/text/heading/x)
- Looks good with `Text` and heading `sm/md`.
- Checked with @MiguelGDLR --> from UI perspective it's way better.
- ⚠️ not a pixel perfect solution, but …
=> fix: section message icon spacing

lib/CONTRIBUTING.md, lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap, lib/src/components/chip-toggle-group/__snapshots__/ChipToggleGroup.test.tsx.snap, lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap, lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap, lib/src/components/stepper/StepperStepContainer.tsx, lib/src/components/stepper/__snapshots__/Stepper.test.tsx.snap, lib/src/components/tabs/__snapshots__/Tabs.test.tsx.snap, lib/src/components/tile-interactive/__snapshots__/TileInteractive.test.tsx.snap, lib/src/components/tile-toggle-group/__snapshots__/TileToggleGroup.test.tsx.snap, lib/src/components/toggle-group/__snapshots__/ToggleGroup.test.tsx.snap, lib/src/utilities/style/focus-visible-style-block.ts
Some uses of `$primary` were missed in the previous replacement, particularly the one which does all our focus rings :o
Focus outlines are back on the menu boiz.
**before**
(the first tile is focused can't you tell?)
**after**
=> fix: stray uses of color $primary which had not been replaced

lib/src/components/stepper/StepperStepForward.tsx
We have a condition in the component that makes the `children` prop optional. This wasn't reflected in the types.
=> fix: make the children prop optional on the Stepper.StepForward component

.github/workflows/stale.yaml
**Description:**
After running the stale GH action successfully on our main repo, this PR introduces the same conditions in this repo
This task will use the off the box functionality of GitHub to close PRs and issues that had no activity in a long time.
NOTE: the PRs and issues are closed, not deleted, so there is no loss of code or information.
**Why?**
- To avoid the temptation of trying to reinstate a PR that has been stale ( has been the source of many bugs in the past as the code base evolves too quickly now that we are a larger team)
- To avoid clutter and make it easier to see what is pending
- To avoid having people be tagged in notifications (in Slack) on PRs that are stale
**Implementation**
This current config which we can adapt,
- will comment on the PR if it had no activity …
=> chore: add stale githubaction

lib/src/components/checkbox-group/CheckboxGroupAllItem.tsx, lib/src/components/checkbox-group/__snapshots__/CheckboxGroup.test.tsx.snap, lib/src/components/checkbox-tree/__snapshots__/CheckboxTree.test.tsx.snap
Ensure all checkbox items in a group are not checked when mounted. 
https://github.com/Atom-Learning/components/assets/3226804/c4ce0cf7-dbf1-4932-995c-1f1765ef7303
https://github.com/Atom-Learning/components/assets/3226804/e695cd38-7d41-462a-bc3d-c50473751f28
https://github.com/Atom-Learning/components/assets/3226804/cdae8d5e-af3a-40cf-b71a-3fac1e42b8d4
https://github.com/Atom-Learning/components/assets/3226804/8c65866e-c5c9-49c9-b909-31e419470575
=> Fix: Checkbox Tree flash of checked

lib/src/components/pagination/Pagination.test.tsx, lib/src/components/pagination/Pagination.tsx, lib/src/components/pagination/PaginationPopover.tsx, lib/src/components/pagination/types.ts
This ticket is part of this B2B ticket:
https://atomlearningltd.atlassian.net/browse/B2B-651
AS A Quest student
I WANT to find the navigation easy and intuitive, even if I am a 5-year-old
SO THAT I can do my best in the assessment without being confused or distracted
The pagination popover is exactly what we needed to display, just with a different trigger, and no horizontal numbered list of pages.
I considered pulling the <PaginationPopover> component out so it could be added directly, but it would need the Provider and ColorScheme around it, and that quickly seemed impractical.
So I have added a couple of new props, to turn the "popover only" view on, and specify what the trigger looks like. 
I'm open to suggestions on naming and other alternatives but this seems like a really neat way …
=> B2B-651 - Custom popover view for pagination

documentation/content/components.toggle-group.md, lib/src/components/chip-toggle-group/ChipToggleGroupRoot.tsx, lib/src/components/tile-toggle-group/TileToggleGroupRoot.tsx, lib/src/components/toggle-group/ToggleGroupRoot.tsx, lib/src/utilities/radix-overrides/index.ts, lib/src/utilities/radix-overrides/toggle-group/ToggleGroupRoot.tsx, lib/src/utilities/radix-overrides/toggle-group/index.ts
@AtanasKovachev pointed out that fields using `ToggleGroup` component were deselecting values on double click.
After @mzeenkala23 and @Marcdup1 investigated they pointed out that the radix component itself has this functionality.
This makes sense in the context radix is using this component but not the context we sometimes are.
This PR adds an override to radix's base root component to `disableDeselect` (open to prop renaming suggestions) which doesn't let the component become empty after a value has been originally selected.
It then uses the root override in all the places where we have toggle groups so the functionality is shared across them.
**before**
https://github.com/Atom-Learning/components/assets/6905473/ce2da80c-65a5-4f21-aa7c-91489d7bbbbe
**after**
_(when cursor is over toggle …
=> feat: disableDeselect ToggleGroup functionality

documentation/content/components.pagination.md, lib/src/components/pagination/Pagination.tsx, lib/src/components/pagination/PaginationPage.tsx, lib/src/components/pagination/PaginationPopover.tsx, lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap, lib/src/components/pagination/types.ts
This is the new design of pagination indication. Changed from the small dot underneath, to a filled in background in primary brand colour.
https://www.figma.com/file/ZifX47jNu7xs568i8KFuVj/Quest-live-session?type=design&node-id=3167-6129&mode=design&t=CcLpPco9wv5y2Ctz-0
DESIGN:
Implementation:
Focus on 4 (selected)
Focus on 1 (indicated)
No focus, 2 indicated
Focus on 2 (indicated and selected)
=> B2B-651 - Pagination - Replace dot indication style with solid bg

documentation/content/components.data-table.md, lib/src/components/data-table/DataTable.types.ts, lib/src/components/data-table/DataTableContext.tsx, lib/src/components/data-table/DataTableRow.tsx, lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap
Adding option to display disabled rows on the Data table. This is a visual change only so the elements in the table will still be clickable and the reason for that is to give more flexibility allowing the consumer of the component to decide if a disabled row can be selected or expanded.
=> feat: data table disabled rows

lib/src/components/navigation/NavigationMenu.tsx, lib/src/components/navigation/__snapshots__/NavigationMenu.test.tsx.snap
Set the navigation viewport offset to a css variable so we can use it to reset the translate if needed - for example if we have a full width dropdown item.
**Example usage:**
```
<NavigationMenu.DropdownContent css={{ width: '100vw', transform: 'translateX(calc(-1 * var(--navigation-menu-viewport-offset)))' }}>
```
**Before**
https://github.com/Atom-Learning/components/assets/6905473/4577e002-ee37-49db-9627-029e1fa0b5d6
**After** (using the code above)
https://github.com/Atom-Learning/components/assets/6905473/2fea5457-6d95-45db-8449-60b8f9b78935
=> feat: make NavigationMenu viewport offset a css variable

lib/src/components/chip-toggle-group/ChipToggleGroupItem.tsx, lib/src/components/chip-toggle-group/__snapshots__/ChipToggleGroup.test.tsx.snap
Setting the background colour white to the active chip toggle group item, that was being removed since we don't have the `$white` token and causing issues when the bg is similar to the borders and text colours.
Before:
After:
=> fix(chip-toggle-group): fixing active chip toggle background

documentation/package.json, lib/package.json, lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap, lib/src/components/badge/__snapshots__/Badge.test.tsx.snap, lib/src/components/banner/banner-regular/__snapshots__/BannerRegular.test.tsx.snap, lib/src/components/banner/banner-slim/__snapshots__/BannerSlim.test.tsx.snap, lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/drawer/__snapshots__/Drawer.test.tsx.snap, lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap, lib/src/components/navigation/__snapshots__/NavigationMenu.test.tsx.snap, lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap, lib/src/components/side-bar/__snapshots__/SideBar.test.tsx.snap, lib/src/components/tabs/__snapshots__/Tabs.test.tsx.snap, lib/src/components/tile-interactive/__snapshots__/TileInteractive.test.tsx.snap, lib/src/components/tile-toggle-group/__snapshots__/TileToggleGroup.test.tsx.snap, lib/src/components/tile/__snapshots__/Tile.test.tsx.snap, lib/src/components/top-bar/__snapshots__/TopBar.test.tsx.snap, yarn.lock
We've updated the colours to include new palettes for Marsh, Maroon and Lapis, plus updated colours for Quest.
This just bumps the theme version from 3.0.1 to 3.1.0 and updates the snapshots
=> chore: updated theme version to include new colours

documentation/content/components.data-table.md, lib/src/components/data-table/DataTable.test.tsx, lib/src/components/data-table/pagination/Pagination.tsx
https://atomlearningltd.atlassian.net/browse/HMP-739
With the update of the pagination in the Design System table we now display the component even if the table has only one page or no data returned. This isn’t necessary when the user has no other pages to access.
1. If a table has only one page (less than the maximum amount of items that can be fit on one page), do not display the pagination (Implemented in this PR)
2. If a table has no pages (The empty state shows), do not display the pagination (Already in place)
3. If a table has more than one page (more than the maximum amount of items that can be fit on one page), display the pagination as expected (Already in place)
Implementation -
1. Conditionally rendering Pagination component based on page count
2. Added unit test
Screenshots - …
=> Feat: Render pagination component only if there is more than one page

lib/src/components/calendar/Day.tsx, lib/src/components/calendar/__snapshots__/Calendar.test.tsx.snap, lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap
Adding disabled layout to days out of the range passed to the date input field. The days were already disabled so users cannot select them but there was no visual feedback that those days couldn't be selected.
=> fix: adding disabled style to dates that cannot be selected

lib/src/components/tile-interactive/TileInteractive.tsx
I was trying to make a `TileInteractive` be a `Dialog.Trigger` to open a dialog but what I was passing into `as` was not being respected. 
This code tweak makes sure that if something is explicitly passed into `as` it is preferred over the accessible overrides of `a` or `button`.
_**Note that**_ this means if you pass `TileInteractive as={Flex}` it will end up being a `div` and not an anchor or button - which is wrong semantically for an interactive element. So be very conscious of that.
From a scan into the codebase we do not override `as` on `TileInteractive` at all so far (assuming cause it didn't use to work anyway) but now that we have the ability we need to be cautious when choosing to do so.
**with sandbox code:** 
```
const App = () => (
<Flex
css={{
minHeight: '100vh', …
```
=> fix: respect "as" prop when explicitely passed in TileInteractive

lib/src/components/accordion/Accordion.test.tsx, lib/src/components/accordion/AccordionTrigger.tsx
Followup for: https://github.com/Atom-Learning/components/pull/663
The previous PR didn't fully fix the issue. It rendered the correct elements, but it passed the `Accordion.Trigger` props onto the `React.Fragment`, instead of the actual child components 🥲
=> fix: props being passed to a fragment with `asChild` in `Accordion.Trigger`

documentation/pages/_document.tsx
Due to reports of polyfill(dot)io now being owned by a malicious actor, we are replacing all instances of it with CloudFlare's mirror
=> security - replace polyfill(dot)io with CloudFlare mirror

lib/src/components/empty-state/EmptyStateBody.tsx, lib/src/components/empty-state/EmptyStateTitle.tsx
There is a TS error when using `as` with the EmptyState subcomponents
```
Property 'as' does not exist on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "size" | "css"> & TransformProps<...> & { ...; }'
```
Adding `as` prop to `EmptyState.Title` and `EmptyState.body`
=> fix: add `as` prop for empty state title & body

lib/src/components/date-input/__snapshots__/DateInput.test.tsx.snap, lib/src/components/input/Input.tsx
Replaces Override with explicitly Omitting. 
Also tiny fix for proptypes.
=> fix: do not use Override in Input types

package.json, patches/@stitches+react+1.3.1-1.patch, yarn.lock
Our machines were running out of memory when running `tsc`, turns out this was caused by this issue:
https://github.com/stitchesjs/stitches/issues/1038
This PR applies the patch described here:
https://github.com/stitchesjs/stitches/issues/1038#issuecomment-1516638929
Note that this patch will only be applied when installing packages at root level, we should upgrade `yarn` (or move to `pnpm`) so that we don't need `patch-package` and instead can just use the built-in patch functionality of `yarn` / `pnpm`.
=> fix: add patch to fix memory usage issues with Stitches type

lib/package.json
When we switched to `semantic-release-yarn` the default package registry was set to the yarn registry, this reverts that change.
=> fix: set the package registry

.yarnrc.yml, documentation/components/markdown/editor-component/Cards.tsx, documentation/components/markdown/editor-component/DosAndDonts.tsx, documentation/package.json, lib/package.json, lib/src/utilities/hooks/useResizeObserver.ts, lib/src/utilities/hooks/useScrollPosition.ts, lib/src/utilities/hooks/useWindowScrollPosition.ts, yarn.lock
Fixes to get the documentation site up and running again:
- Downgrade `remark-gfm`: https://github.com/contentlayerdev/contentlayer/issues/558
- Revert `nodeLinker` back to `node-modules`: https://github.com/vercel/next.js/issues/65757
Also fixed a few type errors that came up during the build.
=> fix: revert to node-modules nodeLinker and old remark-gfm package

package.json
When building the the documentation site with the new NextJS version it failed typechecks, because the types for the library weren't built with the `build:lib` command.
=> fix: build lib types on the main build command

lib/src/utilities/style/focus-visible-style-block.ts
Adds option to pass in `boxShadow` to the `focusVisibleStyleBlock` css generator.
This was needed for the `Answer` component's border, which is coded with boxShadow so as to not change the answer size onSelect. (see video)
https://github.com/user-attachments/assets/894cb941-5a03-4974-ab55-5224d03576f1
Required for PR: https://github.com/Atom-Learning/components/pull/703
=> feat: focusVisibleStyleBlock allow boxShadow to be passed in

lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap, lib/src/components/input/Input.tsx, lib/src/components/search-field/__snapshots__/SearchField.test.tsx.snap, lib/src/components/search-input/SearchInput.tsx, lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
`className`s passed into `Input` were being added to `InputText` (the field) and not the wrapping `InputBackground`.
This is a problem when it comes to adding spacing or handling sizing either with `styled` or `css` from the parent as it skips a div.
Placement on the `InputBackground` which is the outer element should be more correct.
The `SearchInput` component was affected by this change, with the area where the icon is placed not being clickable anymore (click through to input for edit). This was amended via slight restructuring and now the component should have no visual or functional changes. ( https://github.com/Atom-Learning/components/pull/702/commits/4a5f1ca0ec175413f2b9d53a968338ca32fd5f25 )
This work is required for PR: https://github.com/Atom-Learning/components/pull/703
=> fix: classname placement on Input

lib/src/components/navigation-menu-vertical/NavigationMenuVerticalText.tsx, lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap
When reduced motion config is turned on the navigation texts were being displayed even when the navigation was not expanded, that is because the opacity was being set under the allow motion media query.
**Before**
In this PR I'm moving the opacity out of the media query so it can be set even if motion is reduced, keeping only the animation changes to this media query.
**After**
https://github.com/user-attachments/assets/bbbd10f8-6df1-44d7-be28-aa9f63cf1298
=> fix(navigation-menu-vertical): changing text opacity even if motion is reduced

lib/src/components/top-bar/TopBar.tsx, lib/src/components/top-bar/__snapshots__/TopBar.test.tsx.snap, package.json
https://atomlearningltd.atlassian.net/browse/HMP-1178
We encountered a bug last week where TopBar was not rendering well with other elements in the page
Upon investigation, we found out that overriding z-index of the root of TopBar component fixed the issue. However, it was done so by forcing the override from outside. This PR enables css overrides for root / wrapper element of TopBar. After this is released, we will remove the forced override and pass the required css as a prop instead.
More information - https://github.com/Atom-Learning/atom-core/pull/10161
=> Feat: Allow CSS overrides for TopBar wrapper element

lib/src/components/chip-toggle-group/ChipToggleGroupItem.tsx, lib/src/components/chip-toggle-group/__snapshots__/ChipToggleGroup.test.tsx.snap
Updating Chip item background to white when not selected, the grey background was causing confusion with the disabled state.
Jira: https://atomlearningltd.atlassian.net/browse/B2B-835
Figma: https://www.figma.com/design/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=3555-10163&node-type=frame&t=FknpJmcQhPRtWab8-0
=> chore: changing chips background color
